---
bibliography: references.bib
---


# Turkey Trip


Notes from [Walking the Text](http://walkingthetestcom) trip to Turkey September 12-24, 2021

- Day 1: Tuesday 9/14
  - Vaclav Museum 
  - Antalya Museum 9/14  
  - Perga Muratpasa.  Harbor. Antalay Museum 10am.  Perga
- Day 2: 9/15 Weds  Gorguorta Mh (outside Yalvac). Museum
  - Colossae????
- Day 3: 9/16 Thurs Denizli Frontinus Gate and Heiropolos (spring). Pamukkale Pools 12pm. Denizli 2pm
  - Laodicea 
- Day 4: 9/17 Fri 
  - Philadelphia
  Tetrapylon Aphordisease Antik Kenti.  Sean Jean Slisesi. Museum with god-fearer inscription. Sebastion reliefs (in museum). Sebastion on site 10am. Huge stadium 11am
  - Aphrodisias city of Marble
- Day 5: 9/18 Sat  Manisa (Vineyardn 9am). Sardis 11am.Artemis Tapinagi 12pm.  Small city park Ragip Bey Mh 5pm
- Day 6: 9/19 Sunday   
  - Ulucamii Mh 9am. 
  - Kurtulus Mh 9:30am. 
  - Theater and temple to Dionysus 10am 
  - Selcuk Mn 12:20pm. 
  - Zafer Mn (Aesculayeon). 
  - Pergamum
  - Smyrna 4pm
- Sabbath
- Day 8: 9/21 Tuesday 
  - Ataturk Mh 10am.  
  - Mt Croessus.
  - Selcuk (Ephesus) museum 1pm. 2 statues of Artemis. 
  - Ephesus Ruins (first day) Pierene
- Day 9: 9/22 Wednesday. 
  - St Jean Kilisesi. Focus on Revelations. 
  - Villas in Ephesus. 
- Day 10: 9/23 Thursday. Didyma. Miletos. Priene?

# Day 1

## Devotion

Who are you? What are you doing here?

Ez 40:4

> And the man said to me, “Son of man, look with your eyes, and hear with your ears, and set your heart upon all that I shall show you, for you were brought here in order that I might show it to you. Declare all that you see to the house of Israel.”

## History Timeline

### Alexander the Great

Alexander the Great defeats Persians

301BC   Battle of Ipus. After his death, kingdom was split between four generals:

- Lysimacus - Western Asia Minor
- Seleusus I Nicator - Eastern Asias Minor and North Syrin (later attacks Lysimicus)
- Ptolemy - South Syria and Egypt
- Cassander - Macedonia

Israel alternated control by either Ptolemy or Seleusus.  Antiochus IV (Seleucid) offends Jews with the abomination of desolation 

### Roman Empire

Problem: How to forge a Roman identity across the empire?

Virgil commissioned to write the Aenid as an origin story for Rome starting with the burning of Troy (where Homer's Iliad leaves off).  "The ox and the lion will lie down together"

### Juius Caesar

61BC - Julius Caesar comes to power. Enemy was Pompeii, and a civil war broke out. Pompeii was subsequently assassinated in Egypt. 

59BC - comet appears and this is claimed as a sign that Caesar is divine. 

44BC - Julius Caesar was asasinated by Bruts and Cassius.

Caesar's will names Octavian, his nephew, as next roman leader. 

### Octavian (Caesar Augustus)

Octavian assumes power at age 18

43BC - Triumverate: Octavian, Mark Anthony, Lepidus. Lepidus is subsequently dismissed. 

31BC - Battle of Actium - Octavian defeats Mark Anthony. Mark Anthony had married Cleopatra, with whom Julius Caesar had ha a relationship. 

29BC - Pergamum proposes to build a temple for Octavian. He agrees, with the condition that temples are built for Roma and Julius Caessar in Ephesus.

27BC - Octavian offers to yield power to senate, which subsequently make him the first emporer


### Emperors

- Caesar Augustus 27BC - 14AD
- Tiberius 14AD - 37AD
- Caligula 37AD - 41AD
- Claudius 41AD - 54AD
- Nero 54AD - 68AD
- Vaspasian 68AD - 79AD
- Titus 79AD - 81AD
- 

### Roman Triumph

- Required killing at least 5,000 enemy soldiers (civil war did not qualify)
- INitially could be arranged in honor of a general, but later was only used to celebrate the emperor.
- Designed to emphasize divine approval of the emperor
- Order of procession:
  1) Praetorian guard (legions were not permitted in Rome except on permission of emperor)
  2) Caesar dressed like a god with a purple robe, golden wreath, sceptor or reed in his hands
  3) Soldiers "Hail Caesar"
  4) Procession to Forum
  5) Sacrificial bull with the instrument of his death (eg hammer)
  6) Conclusion at Capetine Hill
  7) Caesar offered cup of wine as libation - poured out on head of bull 
  8) Bull is then sacrificed
  9) Caesar ascends (with someone on left and right)
  10) Look for divine sign - flock or birds or an eclipse
  
  John's gospel draws parallele between triumph and crucifixion
  
  Mark 15:6
  
  Mark 15:17
  
  Mark 15:18
  
  Mark 15:20
  
  Mark 14
  
  Mark 15:24
  
  Mark 15:28
  
  Mark 15:29
  
  I Cor 2
  
  Col 2:15
  
  Mark 1
  
  
  Priene Calendar Inscription "beginng of good news of Caesar son of God"
  
  At crucifixion, no one was able to figure out true identity of Jesus, which required a Roman centurion
  
  I Cor 4:15  Leads us as captives
  
  We are the aroma...

## Regions

### Syria

Modern day Palestine (Levant). Province of Syria important to Romans to protect them from the Parthians in the East and from Jewish rebellion in Judea. Quirinius appointed Syria Governor in AD 6^[Wilson, p58]

### Antioch on the Orontes

After death of Alexander the Greek in 306BC, Antigonous I controls Antioch.  After 

### Roman Gods

Artemis

Zeus

Hygei

Apolo

Hermes - Messenger. God of Commerce

Hercules/Paracles

Aesculapyus - God of Medicine.  symbol of snake- who would shed skin and regerate.

### Helenism

Alexander the Great - Was a missionary spreading a message of Helenism

- Changed culture and sports
- Brought an individualistic mentality
- Sex and alcohol to excess


