---
bibliography: references.bib
---

# Antalya

## History

-   Founded by Attlus II
-   190BC Antiochus III defeated at battle of Magnesia by Romans + Pergamenes against Seleucid kin For events of Antiochus III See Daniel 11:10-19
-   188 BC Treaty of Apamea
-   133 BC - Attalus III willed lands to Rome, but Atalya remained free
-   64 BC - Rome annexed Atalya by Pompey
-   40-39 BC Parthians occupied Antioch on the Orantes

## Saul

-   Acts 7:5-8 They laid their coats at the feet of Saul
-   Acts 8:1-3 Saul approved of their execution. He put beleivers in prison.
-   Acts 21:39 (arrested on temple mount
-   Ats 22:3

### Tarsus

171BC citizens of Tarsus began receiving Roman citizenship. 64BC Capital of Cilicia. Site of largest philosophy school in the empire

### Gamiel

Acts 22:3 Studied under Gamiel in Jerusalem (required \$)

Gamiel - First rabbi (my teacher) given title of rabboni (our teacher)

-   Grandson of Hillel, who died when Jesus was 20. More tolerant and progressive than Shamai. Jesus tended to favor teaching of Hillel (except about marriage)

Acts 5:30-40 Gamiel (honored by all):

> "If (the Way) is from God, you will not be able to stop it, because you cannot oppose God.

Acts 9:1 Saul - asked for letters for Damascus (150 miles away) to take them as prisoners

Acts 22:3

Acts 22:3-21

Acts 20:9-18

Galatians 1:3-7

# Antalya

Acts 9:34 Damascus Saul,Saul

Ez 1:28 Rainow / Glory -\> fell face down

Acts 9:15 GO -\> proclaim my names to the Gentiles

Gal 1:15-16 God set me apart from my mother's womb

Is 49 Called me from my mother's womb -\> light to the Gentiles

Jer 1:5

Paul arrives in town -\> goes to synagogue first

Acts 9:9

Acts 9:4

Jonah - 3 days in the whale

Fighting against the goads

Gamiel -\> if the Way is from God, you cannot resist it, because you would be resisting God

Playwright from the day (Euripidies): futility of resisting the gods- kick against the goads.

Gal 1: Gospel is not of human origin. As zealous as any

## Zeal

Hebrew: Kana' Phineas Num 25 EliJah I kings 19:10 I have zealously served the Lord Zealots - politica group in the Inter-testimental period - Zealous and stopping at nothing - Maccabean revolt AD6

Ps 69:8-9

## Paul went to Arabia (=wilderness)

I Kings 19:15 Lord says to Elijah: return to wilderness

Gal 1:17 I did not go up to Jerusalem but went to Arabia

Gal 4:25 Hagar is Mt Sinai in Arabia

(Province of Arabia is Siani penninsula - NOT Saudi Arabia)

## Wilderness

God meets people in the wilderness - Moses, Issrael, Elijah, Paul

Paul spends 3 years in the wilderness getting his theology right. He was zealous in persecuting the Way, but needed to re-orient his theology.

Acts 13:13 Pamphylia

Acts 14:25-26 Perga -\> Atylia -\> Antioch

#Ephesus

## Geography

Mount Coresssus - Hiked

Mount Pion - across valled with two humps

City with castle - Mount Ayasoluk

To left -river at base of mountains Cayster river

Oval - marshlike - Harbor - at base of where we hiked - silting of Cister river. Water is not now 3 miles away

Teater at base of mount Peon could hold 20,000 people

Road goes from amphitheater to harbor = "Harbor Street"

Teater to covered building - Marblestreet

Building to smaller theater - Curets streeets = Curetes Street. Between teaheater and flat room - Giant swaure with trees in middle = agora - Commercial agoara

Big square with theater on it Civic Agora

Perga - One agora

Hiked Moutn Caresis

Mount aslaouke in distance

Three major roads - harbor/mlarble/curet street Commercial and state agora

Mgnesin gate - near bend in road outside parking lot.

Started our hike when wall goes down back side.

5 mile wall built by Lysimicus to protect city

Stadium on NorthEast of ed

Artemesis temple largest in the world only a solumn remains. Off North end of Moutn Peopls headed towards moutn Ayosolupe. Wasn't in city center because something fwll from sky - probably piece of meteor. Built temple in swampy area. Birthplace of artemesis was behind MOunt Caresus in Mount Ortygia.

Ephesus means "desirable"

Huntington College Mark Fairchild - similar to Mark Wilson

Origin myth - Amazons founded Ephesus and cult of Artemis. Amazone are Hittites. From Black Sea region.

Amazons - all-woman tribe amazinzg archers.

Ephesus founded 1900BC

Local peoples 1100 to 1000 BC (during time of David - Uriah the Hittite is from Turkey)

Greek colonists -\> Greek influence. Settlement situated city off North side of Moutn Peon about 1000BC unto 550BC (off North end of Mt Peon.

560BC - Cresus - Lydian King takes control of city, then moves city further twoards Mount Ayosolyou.

Cresus is rich - See notes from Sardis -

546 - Cresus is owned by Cryrus the Persian

334 BC conqurered b Alexander th Great. Preserves city (Macedonia control)

Alexander the great dies -\> generals fight.

294 BC Lysimicus gains control of EPhesus. Lysimicus moves city to between Mount Caressus and Moutn PePeon.. Lysimicus bruilds 5 mile wall to protect city.

282 BC Celscids defeat Lysimicus.

Philaterus city steward of Pergamum. Sides sith Celusis, whoo defeats Lysimicus

Battle of Magnasia

Celusids lose to Romans and Attelids

133BC Attelid III dies and wills empire to Rome.

Added to Provice of Asia 129 BC

First Century AD: Ephesus suppants Pergamum as foremost city in Asia. Fourth larges city in Roman empire behind rome, ayrian antioch, Alexandria. Ephesus and Syrian Antioch ar similar sin sizse Minimum 250,000 people in Ephesus in APaul.s days

Leadership in Ephesus:

Acts 18:18-21

> Paul stayed many days, set sail (from Corinth) with Aquilla and Priscilla.

Paul was trying to come to Ephesus, but prevented by Holy Sprit. On Second missionary journey, drops off Aquilla and Priscilla.

Acts 14:24-28

> Jew named Apollo. Had been instructed in the way of the Lord. Knew only baptism of John...proving from the scriptures that Jesus was the Christ

Acts 19:1

> While Apollos was in Corinth. Paul took interior road (3rd Journey - has with him since Lystra = Timothy)

Acts 20:31

> Be on your guard. For 3 years I have never stopped warning you with tears.

Acts 19:22

> timoyh. styed in Asia and pastors Church

II tim 4:11-13

> Only Luke with mith me. Get Mark. I sent Tichicus to Ephesus.

Tichichus is pastoring in Ephesus. Timoty was buried at Ephesus. Luke is buried at Ephesus. After this. John comes to Ephesus and becomes pastor in Ephesus. At foot of corss - John behold you mother, Mother, behold your son.

Church of Mary. Mother of Jesus died here.

Long list of people pastoring in Ephesus.

Ephesus a gateway city for Troas to the East. Connect Agean to Asia

Only more highly travelled area is Israel.

Aprodesian 1750 people in Bouleterion

Built 2C AD

Constructed in Hellenistir period (Begins with Alexander the Great)

= 334 BC and followings.

Boule meeting - only members of counci could enter and vote. Otherwise could be used as Odeon (lecture hall)

Acts 19:

18 Months in Corinth -\> Ephesius. Leaves Priscilla and Aquilla

Apollos - needs to hear about holy spirit.

Appolos sthen goes elsewhere

Acts 19:1

> Apollos at Corinth. Paul took road through interior to Ephesus. Have you heard of Holy Sprit\> -\> Jhn's Baptism. thhey were baptized in name of Jesus and holy spirit am on them and they spoke in tongues and prophesized

John ws populatJohn'smission was to prepare the way for the messiah. Baptism of repentence.

v4

Third missionary journey - 54-55AD, 25 yeaers after resurrection - people still are talking about John's baptism.

Story of Jesus had still not been procolaimed in Ephesus.

First journey 46-48

Acts 15 council 49-50

2nd Journey 50-53

Third journey 53-54-57 AD.

Arrested in Jerusalem

Cesearii

Rome in 60--61

61-2 Paul released

Light chain arrest Pilat 26-36 AD -\> felxi festus -\> agrippa

When in Rome, he is not in a prison cell. He has a right to appeal to Caesar.

Being guarded by a soldier. 64 - our

Rearrested in 67 -\> brought ot Nero. Paul martyred by Nero 67=68 AD

For 3 years I warned you

9 months unaccounted for

3 mo synagogue - 2 mon lecture hall -\> gap 9 months -\>

... so that all the Jews and Greeks heard the word of the Lord.

Seven sons of Sceva. Jesus I now, and I know about Paull, but who are you?

Magical center of Roman empire. Curses, Voodoo, incantations. Paul has a power that is coming from a different source of power.

Drachama -= 1 days wage. 50,000 drachamas went kukp in flames

Word spread widely and grew in power. Handkerchief gig only happens in Ephesus. A number who had practiced socercery

Huge bonfire " we are starting church" see also in Timothy, Ephesiand, Corinthians. Start of church amidst chos.

False teaching is going to be a huge problems.

Sorcery =/= cult worship.

note lions feed oflanking staris

Alexander offered money to hepl rebuild, and offered money for rebuilding.

Four times size of Parthenon. 400+ feet long, 200+ feet wide. Forest of 127 columns

Sevveral function

pilgrims banking governmentl inscriptions Asylum Debtors Poor and Needy

Controlled 70,000 acres of agriculture.

#Theater - started being removatd in 60AD

Ima Kevea + media keea + summa keveah

\## Artemesian = Artemis temple One ov 7 wonders of the ancient world

1000s of pilgrims came for Spring festival of Artemis

At new testament time, temple ws 5th one built on the site. Built and rebuilt, renovated.

Located at site of meteroite falling. Traditional birthplace behined moutn Paresis.

July 21, 356 BC Herostratus burned down temple with oil lamps and rags. Ruler banned use of his name, and baned . Herostatic fame"

Dishonoring that goddess would let the temple burn. Date is birthdate of Alexander the Great MOther goddess left her post to attend the birth of Alexander the Great

Richest sancuart apart for oracle at Delphi

Ortesia - sacred grove where she was born = Ortesia described as "paradise" = paradeisos There arose a great disturbance about The Way. Demetrius a silversmith brought in small little business for the skilled wrokers "You know, that we received a good business, and how Paul has convinced... practically the shole province of Asia .

Acts 19

> They shouted for two hours: "Great is Artemis" in the theater

Preitanus (City Clerk) quieted the crowd. (It took him two hours to get there)

People of Ephesus, doesn't all the world know that Ephesus is neocorus of the temple of Artemis and her image that fell from heaven. Since these facts are undeniable.

Though they have neither robbed tamples or blasphemed...

IF then, Demetrius and his associates have a grievance, they can bring it to the procounsel.

As it is, we are in danger of being charged with rioting, since there is no reason for it. With that, he dismissed the assembly.

Paul was having a massive impact on the city, bot by tearing down their gods, but by evelating the gospel.
