---
bibliography: references.bib
---

# Colossae

## Geography

Mount Cadmus is source of water

## Culture

Red-purple dye = Colossinus

## History

Tell not yet excavated

480BC Xerxes (Persian) invaded

Leading city 5/6 Century BC

300BC Heropolis built

60 AD - Earthquake decimated

5/6 Century AC -\> people moved out

## Biblical References

Paul took road through interior to Ephesus on 3rd missionary journey Paul never met Colossains Letter written by Paul from Rome - Delivered by Tichichus

## Ephesians 4: Instructions to Families

### Domestic Relationships in Roman culture

Aristotle Politics: Household management in its perfect form: master + slave, husband + wife,

449BC - Law on 12 Tablets

Pater Familia - held power of life and death for household members

### Ephesians 4

Paul didn't invent Roman household code. Instructions are given first to wives, then husbands (pater familias), then children. Addressing wives first was unheard of in Roman society.

### Marriage types

-   With the hand - Man brings a women into his home (and she is subject to him) - 50%
-   without the hand - Wife is not under husband's authority

### Instructions to husbands

Husbands - Agapao - love without expecting anything in return. This was revolutionary in Roman culture, which was highly transactional. Many marriages were politically expedient

Work for master - LORD: Kuios

### Slavery

Paul couldn't abolish slavery, as the whole economy of the Roman Empire depended upon slavery.

### Instructions to children

Children - when asked to obey - assumes agency
