---
bibliography: references.bib
---

# Perga

# Culture

70AD Gladiators introduced to Perga - Generally a spectacle associated with a festival.

12,000 spectators

Jail was used simply to hold prisoners over until execution.

Romans were first to build free-standing theaters (Greeks built them into the hillside)

Outer Gates - 300AD Inner gates XXBC

Baths - Most popular form of leisure activity

Greeks - gymnasium - used primarily for exercise. gymnos = naked

Romans - More emphasis on waters. 867 bath houses in Rome

"Baths, wine, and sex spoil our body and make our life"

Apodyterium - changing room

### Agora

Civie agora

Commercial agora. Inside square - statue of Hermes

Cardo - Usually north-south main street Decuminus - east-wests main street

Nymphaneum of Kystros

## Barnabas and Saul

Acts 13

Acts 14:25

> Set apart Barnabas and Saul

Actis 12:25

Acts 11:36

Acts 9:27 Barnabas brought Paul to council

Acts 11:22 Barnabas -\> antioch. News reaches Jerusalem, which sends Barnabas

Acts 11:25-6: Believers were fist called Christians in Antioch

Col 4:10

Acts xx

I Pet 5:13 Peter calls John Mark a son

Acts 13:X Pathos -\> Perga

I Tim 4:11

Why Barnabaas? Acts 4. He was a Levite native of Cyprus. Someone was needed who was trustworthy (vs Ananiasis and Siphira who lied about the process)

Barnabas vouched for Paul

Paul was culturally bilingual

One year of preparation -\> scattered (?)

Why John Mark?. Mark was cousin of Barnabas and knew Jesus' life

Acts 4:36-42

Spirit didn't tell them where to go

Crucifixion was AD30. First missionary journey was 56AD

Why did John Mark leave?

-   Too old
-   Too Roman
-   Sideways relationship with Paul

Paul confronts Peter on failing to associate with Gentiles

Did John Mark go back to avoid ministry to Gentiles?

John Mark writes gospel/founds church in Alexandria Egypt.

Mark's gospel recounts Peter's story

John Mark was one of the 120 but didn't have first-hand knowledge of the crucifixion

## Common mistakes in interpreting the Bible

90% of stories depend upon location

What other events have happened at that location? - Allusion to geography

Acts 15:36

Paul to Barnabas: Let's visit

Right place to be is in the center of God's will, although not necessarily the safest.

II Tim

> Get Mark and bring him to me, for he is helpful for my ministry
