---
bibliography: references.bib
---

# Vaclav

## \_\_\_ Site

[\#### Nymphaeum](https://en.wikipedia.org/wiki/Nymphaeum) - Water souce. Message: Gods and Goddesses bring you your water

Worship of the gods: Underlying concept is that the gods are angry and need to be appeased.

-   Christians seen as atheists because they did not worship Roman gods
-   Jews were offered exemption to worship of Roman gods by Caesar Augustus
-   Jews later told the Romans that Christians were "not one of us", and should not qualify for the exemption.

Question: As a Christian, do you drink the water in the Nymphaem?

### Sarcophagus

Dead buried above ground

# Vaclav museum

## Paul encountering Jesus on the Damascus Road

## Paul in Antioch in Pisidia

Acts 13:

> Now Paul and his companions set sail from Paphos and came to Perga in Pamphylia. And John left them and returned to Jerusalem, 14 but they went on from Perga and came to Antioch in Pisidia. And on the Sabbath day they went into the synagogue and sat down. 15 After the reading from the Law and the Prophets, the rulers of the synagogue sent a message to them, saying, “Brothers, if you have any word of encouragement for the people, say it.” 16 So Paul stood up, and motioning with his hand said:

## Paul and Barnabas switch roles

### Aristotlean Rhetoric

1)  Resortium - INtroduction
2)  Narratio - Background (vv 17-25)
3)  Propositio - Thesis (v26)
4)  Probato - Evidence (vv27-37) 5: Piratio - Closing argumentn (vv38-41)

Paul was made to bring the gospel to the gentiles.

Acts 13:xx-xx

> “Men of Israel and you who fear God, listen. 17 The God of this people Israel chose our fathers and made the people great during their stay in the land of Egypt, and with uplifted arm he led them out of it. 18 And for about forty years he put up with\[b\] them in the wilderness. 19 And after destroying seven nations in the land of Canaan, he gave them their land as an inheritance. 20 All this took about 450 years. And after that he gave them judges until Samuel the prophet. 21 Then they asked for a king, and God gave them Saul the son of Kish, a man of the tribe of Benjamin, for forty years. 22 And when he had removed him, he raised up David to be their king, of whom he testified and said, ‘I have found in David the son of Jesse a man after my heart, who will do all my will.’ 23 Of this man's offspring God has brought to Israel a Savior, Jesus, as he promised. 24 Before his coming, John had proclaimed a baptism of repentance to all the people of Israel. 25 And as John was finishing his course, he said, ‘What do you suppose that I am? I am not he. No, but behold, after me one is coming, the sandals of whose feet I am not worthy to untie.’ 26 “Brothers, sons of the family of Abraham, and those among you who fear God, to us has been sent the message of this salvation. 27 For those who live in Jerusalem and their rulers, because they did not recognize him nor understand the utterances of the prophets, which are read every Sabbath, fulfilled them by condemning him. 28 And though they found in him no guilt worthy of death, they asked Pilate to have him executed. 29 And when they had carried out all that was written of him, they took him down from the tree and laid him in a tomb. 30 But God raised him from the dead, 31 and for many days he appeared to those who had come up with him from Galilee to Jerusalem, who are now his witnesses to the people. 32 And we bring you the good news that what God promised to the fathers, 33 this he has fulfilled to us their children by raising Jesus, as also it is written in the second Psalm, “‘You are my Son,today I have begotten you.’ Ad as for the fact that he raised him from the dead, no more to return to corruption, he has spoken in this way,“‘I will give you the holy and sure blessings of David.’ Therefore he says also in another psalm, “‘You will not let your Holy One see corruption.’ For David, after he had served the purpose of God in his own generation, fell asleep and was laid with his fathers and saw corruption, 37 but he whom God raised up did not see corruption. 38 Let it be known to you therefore, brothers, that through this man forgiveness of sins is proclaimed to you, 39 and by him everyone who believes is freed from everything from which you could not be freed by the law of Moses. 40 Beware, therefore, lest what is said in the Prophets should come about:“‘Look, you scoffers,be astounded and perish; for I am doing a work in your days, work that you will not believe, even if one tells it to you.’”

Is 49:6

> “It is too light a thing that you should be my servant to raise up the tribes of Jacob and to bring back the preserved of Israel; I will make you as a light for the nations, that my salvation may reach to the end of the earth.”

Yalvac museum

Resgueste - Deeds of Caesar

Ovid - Metamorphasis 8AD Baccus and Philemon

-   Wine never runs out.

Acts 14:21

> But Jews came from Antioch and Iconium, and having persuaded the crowds, they stoned Paul and dragged him out of the city, supposing that he was dead. But when the disciples gathered about him, he rose up and entered the city, and on the next day he went on with Barnabas to Derbe.

Paul wasnt giving up!

> 42 As they went out, the people begged that these things might be told them the next Sabbath. 43 And after the meeting of the synagogue broke up, many Jews and devout converts to Judaism followed Paul and Barnabas, who, as they spoke with them, urged them to continue in the grace of God. The next Sabbath almost the whole city gathered to hear the word of the Lord. 45 But when the Jews\[d\] saw the crowds, they were filled with jealousy and began to contradict what was spoken by Paul, reviling him. 46 And Paul and Barnabas spoke out boldly, saying, “It was necessary that the word of God be spoken first to you. Since you thrust it aside and judge yourselves unworthy of eternal life, behold, we are turning to the Gentiles. 47 For so the Lord has commanded us, saying, “‘I have made you a light for the Gentiles, that you may bring salvation to the ends of the earth.’” 48 And when the Gentiles heard this, they began rejoicing and glorifying the word of the Lord, and as many as were appointed to eternal life believed. 49 And the word of the Lord was spreading throughout the whole region. 50 But the Jews incited the devout women of high standing and the leading men of the city, stirred up persecution against Paul and Barnabas, and drove them out of their district. 51 But they shook off the dust from their feet against them and went to Iconium. 52 And the disciples were filled with joy and with the Holy Spirit.
