---
bibliography: references.bib
---

# Hieropolis

Day 3 9/16

## Geography

Lichus river valley - branch of Meander Interior road to Ephesus Holy city = Hieros + polis

## History

200s BC Antiochus II (261BC - 246BC)

190BC Battle of Magnasia

189 Treaty of Apamea

133BC - Attelis III willed kingdom to Rome

17 AD earthquake (city is located over a seismic fault line)

60AD earthquake

Zenith in 2C BC and 3C BC with 80,000 inhabitants

## Tomb scenes

Lazarus (John 11). Had been dead 4 days. People weren't considered dead dead until after 3 days.

Jesus weeps: feels the pain of death in Lazarus. Sin and death were joined since the Fall.

Resurection: John 20. Mary thought he was the gardener.

God partners with humanity to bring wholeness

## Signs of Jesus

1)  Wedding at Cana John 2
2)  Healing of officials's son Jn 4:43
3)  Healing of paralytic at Bethsaida Jn 5
4)  Feeding 5000 John 6
5)  Walking on water
6)  John 9
7)  Healing of Lazarus Jn 11
8)  Resurrection of Jesus - a new reality. First day of the new week. First day of new life.

New tomb in which no one had been laid

Cross and tomb both in a garden

Theology required an empty tomb

Cor 15 - No hope without resurruction

Gardner redeems the garden

## Garden of Eden

Sin destroys our relationships:

-   With God
-   With ourselves
-   With others
-   with Creation

John 18

Jesus crosses Kidron valley to go to a garden (no metion of Gesthemene).

(Gethsemene = oil + pressing)

John doesnt include "take this cup" or Judas. He wants the audience to know "there is victory in the garden"

Empty tomb represents more than just forgiveness of sins.

Eternal life doesnt' just begin after we die. Restoration of all things means reconciling us to ourselves.

Exile in Babylon occurs because Israel did not give the land a Sabbath.

Jesus doesn't want to just forgive us for our brokenness.

Rev 22: Renewed heaven and earth.

End game is about Shaloam

Discipleship in addition to salvation

### Water = chaos = demonic

Red sea = sea parted

Jordan River = waters parted

Bethany beyond Jordan - Jesus redeems the Jordan river

Battle with chaos by the word (??)

John comes in the sprit of Elijah

Elijah leaves the earth at the Jordan

John channels Elijah - wearing skins, etc

Naamam \~ healing of lepers by Jesus

# Martyrium of Philip

Built 4c/5C AD in honor of Philip, who was martyred 80sAD

Edict of Milan - Constantine made Christianity legal

Who was Philip

1)  Philip the disciple
2)  Philip the evangelist in Acts (who preaches to Ethopian eunich)

John 1:43

> Finding Philip, from Bethsaida (only recounted by John)

John

> Turning to Philip

John xx:20

> Greeks came to Philip in order to speak to Jesus

John 14:8-9

> Philip said: "show us the father"

Apocrypha: Book of Philip

-   Eye condition -\> healed

Church grows in persecution and dies in complacency

Gap between expectations and reality =\> crisis of faith. eg "I can't believe in a God who would allow this to happen"

Modern technology increases our ability to predict the unknown

Life does not allow the same control as our phones

"Get thee behind me, Satan!" When we can die to our expectation, we can be open to his leading.
