---
bibliography: references.bib
---

# Laodicea

To Colossae and Laodicea and those I have not met

Epiphras - Pastor for Colossae

Mount Cadmis - Source of cold water

## History

Village fortified in 260BC

Built by Antiochus II mid 3C BC

190 BC -\> given to Attelid kingdom

17AD Earthquake

26AD Competed with 10 cities to become neokorus for Tiberius, who later chose Smyrna, citing a lack of finances in Laodicea for the project. As a result, the city made it a goal to make money.

60AD after earthquake, Laodicea refused Nero's aid in rebuilding (because of their wealth). Colossae was not given aid by Nero because they were considered "no longer important"

## Economy

1)  Banking center
2)  Medical center specializing in opthalmology. Eye salve collrium (sp?). Demontheses wrote an opthalmology textbook
3)  Athletics and Gladiatorial competition
4)  Black wool - due to high lime content in water. Lime content meant that you might vomit after drinking the water.
5)  Zeno family - "Throne City" cf Plancia Magna, benefactress of XXXX

## Geography

Hot water - hot springs of Hieropollis - brought healing Cold water - Collasae - cool and refreshing

I know your deeds (not "I know your faith" or "I know your theology")

I wish you were hot or cold

You are good for nothing (vs Laodicea - "I don't need a thing")

Church began to take on ethos of the community/city.

When Nero did not provide funding for rebuilding of Colossae, Laodicea didn't help.

So be zealous and repent

We have gotten good at confession (I am off the path) rather than repentance (returning to the path).

God loves repentance (cf David sins and then repents)

Imperatives:

-   Hear
-   Be zealous
-   Repent

Roman soldiers had the right to knock on a door and come in to be garrisoned and supplied, and ask for clothing for colleagues.

"sup with you" = Deepnon (?) in greek

Multiple copies made of Revelation - each church sees the letters to the other churches, so that the group of churches can help them repent and can learn from each others' mistakes

Laodicea was midway between Hieropolis and Colossae
