---
bibliography: references.bib
---

# Philadelphia

Day 4 9/17 at 16:30

## Background

1 - "Gateway to the East" 2 - Promoted Hellenistic values

## Culture and industry

Famous for grape production due to volcanic soil. Catacecaumene = "burnt land"

## Religion

Patron saint - Dionysus

-   God of wine
-   God of the arts esp theater
-   God of Spring Break

## History

Founded by Attelis II (ruled 168-158 BC). Nicknamed Philadelphus because elder brother ruled Attelid kingdom (Eumenes II) before him from 197-159BC. In the 160s Attelis II made a trip to Rome, and Rome wanted him to overthrow his brother. Eumenes found out, and named his brother Philadelphus

-   133BC Attelis III wills empire to Rome
-   17AD earthquake decimated. People moved outside city for over a year due to aftershocks.
    -   Tiberius suspended taxes for 5 years -\> in gratitude, name of city is changed to Neocaesarea
-   During Nero, name changed back to Philadelphia
-   60AD earthquake -\> Vespatian provides \$ -\> name changed to Flavia (his wife)
-   92 Domation edict: 505 of all farmland to be sown in grain. This was a problem for the local economy, and the soil would not support growing wheat.
-   After Domitian's death -\> name changed back to Philadelphia.

#Bible

I will make them my pillars -\> my new name

Open door - a gateway that no one can shut.

Pillars - stability You have little power

I will write on (pillars) my new name

Rev 6:10

Is Jesus is gatekeeper to new Jerusalem

Is 60:4-15 Children of oppressors will bow down before you. Then I will call you XXX of my name

Is 45:14 When the bow

Is 49:23 Kings shall be your

I will make (synagogue of satan) bow and acklowledge that I have loved you.

Is 62:1-2 vindication: You will be called by a new name which the mouth of the Lord shall bestow

## Jews and Christians

Jews were granted an exemption to cult worship (ie sacrificing meat to idols), and had to pay a tax

Jews later told the Romans that the Christians were not part of them.

Jews believed that the Christian faith was a farce.

I will keep you from the hour of the test for the whole world (=unrighteous??)

Only imperative: "hold fast" = Krateo eg grab onto a fishing net in the middle of a storm.

All Greek words come from 7 trades

I am coming soon =/= a rapture

I thess 4 Will be augth up together in the cloud. Meet = apantasis. WHen the emporer comes to the city, the citizens go out to meet him and escort him into the city.

Dan 7:13

Dan 7:11 - boastful word: Beast slain
