---
bibliography: references.bib
---

# Aphrodisia

Friday Morning September 17th

City of Marble ( 1 mile from marble quarry)

Origins as small village until 2nd centry BC Growth as artisians began to move from Pergamum Incorporated as city in 1st century BC 44BC Julius Cesar assinated - Brutus and Cassius were responsible - Octavian and Mark Anthony and \_\_\_ form triumverate - Civil war between Octavian and Mark Anthoby vs Brutus and Cassius - Aphrodisia supported Octavian - Labienus and his followers supported Brutus and Cassius - Labienus pillories Aphrodisia for their support of Octavian 42BC Octavian and Mark Anthoy defeat Brutus and Cassius (who commit suicide) 39BC Mark Anthony grants free city status to Aphrosisia for their loyalty to him 30BC Mark Anthony commits suicide after defeat by Octavian (Caesar Augustus) Inscription in wall from Julius Cesar: "I love this city and take it as my own"

## Origin Stories

Homer writes Iliad and Odyssey, which forms origin story for Greece Viril writes Aenid, which connects Greek and ROman origin stories.

Stort starts when Troy is burning (same scene as end of Iliad). Aphrodite (Venus) is father of Aenis

### Emperors connected with Aphrodite in their own origin story

Omrit - 2 miles outside of Cesari Phillipi

-   Temple to Cesar Augustus
-   Status of Venus present =\> Emperor identified with Aphrodite

## Temple to Adphodite

Tetrapylon - Gateway into sanctuary - built 200AD

Temenos - Courtyard Proneos - Front part Neos - Holy of Holies

# Museum

Obelisk - 125 different names of those providing for those in need. Three categories of names:

-   Jews (n=61)

-   Proselytes (n=3) Gentiles who desire to convert to Judiasm. [Wikipedia](https://en.wikipedia.org/wiki/Proselyte)

    -   (Baptized)
    -   Circumcision
    -   Kosher laws

-   God-Fearing (n=52)

Gentiles who want to worship Yaweh but don't want to adopt culture of Jews. [Link](https://www.biblestudymagazine.com/bible-study-magazine-blog/2016/6/3/who-were-the-god-fearers)

Acts 13:16

> So Paul stood up, and motioning with his hand said: “Men of Israel and you who fear God, listen.

Acts 17:4

> And some of them were persuaded and joined Paul and Silas, as did a great many of the devout Greeks and not a few of the leading women.

Acts 17:17

> So he reasoned in the synagogue with the Jews and the devout persons, and in the marketplace every day with those who happened to be there.

## Sebastieon

### Aphrodite

-   Goddess of Love. Usually depicted as sensual

-   Mother Goddess. Statue found in Temple to Aphodite portrays her as mother godess (in full length dress)

Sebastos = venerable one = Greek version of Augustun

The Sebasteion, excavated in 1979-81, was a grandiose temple complex dedicated to Aphrodite and the Julio-Claudian emperors . Its construction stretched over two generations, from c. AD 20 to 60, from the reign of Tiberius to that of Nero. The complex was paid for by two prominent Aphrodisian families. It consisted of a Corinthian temple and a narrow processional avenue (90 x 14 m) flanked by two portico-like buildings, each three-storeyed (12 m high), with superimposed Doric, Ionic, and Corinthian orders. These North and South Buildings, which defined the processional avenue, carried marble reliefs in their upper two storeys for their whole length. The reliefs were framed by the columnar architecture so that the two facades looked like closed picture-walls. Some 200 reliefs were required for the whole project, and more than 80 were recovered in the excavation. They featured Roman emperors, Greek myths, and a series of personified ethne or 'nations' of Augustus' world empire, from the Ethiopians of eastern Africa to the Callaeci of western Spain[link](http://aphrodisias.classics.ox.ac.uk/sebasteion.html)

Temple to Aphrodite and Julio-Claudian emporers (except Caligula)

Reliefs recounted the deeds of the emperor.

Poema = Work of poetra

Eph 2:8-10

> For by grace you have been saved through faith. And this is not your own doing; it is the gift of God, not a result of works, so that no one may boast.For we are his workmanship, created in Christ Jesus for good works, which God prepared beforehand, that we should walk in them.

We are God's Sebastien - recounting of his deeds

> “Do you know what it means that you are God’s workmanship? What is art? Art is beautiful, art is valuable, and art is an expression of the inner being of the maker, of the artist. Imagine what that means. You’re beautiful, you’re valuable, and you’re an expression of the very inner being of the Artist, the divine Artist, God Himself. You see, when Jesus gave Himself on the Cross, He didn’t say, “I’m going to die just so you know I love you.” He said, “I’m going to die, I’m going to bleed, for your splendor. I’m going to re-create you into something beautiful. I will turn you into something splendid, magnificent. I’m the Artist; you’re the art. I’m the Painter; you’re the canvas. I’m the Sculptor; you’re the marble. You don’t look like much there in the quarry, but I can see. Oh, I can see!” Jesus is an Artist!” And you beloved are His crowning achievement, His masterpiece![^17b-aphrodisia-1]

[^17b-aphrodisia-1]: Tim Keller

How do our lives (and deeds) communicate a message about who God is?

I Peter - Living stones buiolt together

Your body is a temple

I Cor 3

I Cor 6

=\> Allow God to shape your life

## Kingdom of Priests
