---
bibliography: references.bib
---

# Sardis Site

Saturday Sept 18th morning

Large site

## History

Founded 1400BC - Center of Lydian Kingdom

Roman province of Asia established 129BC

First community to start dying wool, created dice,

### Heraclips Dynasty.

Earliest rulers: Heraclips - ruled 505 years and 55 kings

Last Heraclips king: Canalves - had beautiful wife. Demanded that his chief bodyguard see her naked to know how beautiful she was. Canalves hid Guyges in his wife's bedroom. Wife discovers Guyges and proposes two options to address her dishonor: Guyges would kill himself, or would kill her husband (for arranging dishonor), and she would marry him. Guyges would become first of Mermnad dynasty.

### Mermnad Dynasty

Heroditis - Mermnad rulers invented coinage

Mining gold in Paltolis river runs between Acropolis and Necropolis

## Battle with Cyrus

Croesus - Mermnad king. Ten years into his rein, debates challenging Cyrus (leader of Persian empire).

Inquires of Oracle at Delphi. Was told: *If you cross the River Hales, a great kingdom would be destroyed*

547BC Croesus crosses the Haley river at Cappodicia to fight Cyrus. Battle ends in stalemate. The end of the fighting season ends, Croesus dismissed the allied armies and heads back to Sardis. Cyrus pursues Croesus and asks the allied armies to join him, ,but they refuse.

October 546BC Cyrus besieged Sardis for one year.

Persian solder observed a Lydian soldier climb down the wall to retrieve a dropped helmet. This observation identified an ara of vulnerability in the wall. A small team was able to breach the wall at night, and open the city gates.

334BC - Sardis remained in Persian control

Conquered by Alexander the Great

220 BC - Celucid king in control

Achaeus usurped authority and rebelled against Antiochus III and pronounced himself king.

Antiochus III besieged Sardis for two years.

Soldier named Lagoris noted that in an area long the wall where dead animals were thrown over the wall, the vultures perched on the wall without being disturbed, meaning that area was not guarded.
