---
bibliography: references.bib
---

# Thyatira

Smallest city, but longest letter

(Why site a city where there is no natural protection?)

3000 BC Lydian town - located near site of Lydian worship of sun god Tyrimnus.

Seleucus I formed a military colony with Macedonian soldiers in 300s BC

190 BC Seleucids under Antiochus III held the city.

188 BC Treaty of Apamea resulted in control by the Attelids

129BC incorporated into Roman province of Asia

## Culture

Manufacturing city:  Bronze working, baking, shoemaking

Acts 16:19  Paul by the river... Woman Lydia from Thyatira, craftsman of purple cloth. (Location would have been Philllipi)

## Deeds

Word used 5x in letter:  ergon  $\epsilon \rho \omega \nu$

James

Faith - pistos $ \pi \iota \sigma \tau \omega \sigma $
Works -  ergon  $\epsilon \rho \omega \nu$

## Food sacrificed to idols

Acts 15:29

>that you abstain from what has been sacrificed to idols, and from blood, and from what has been strangled, and from sexual immorality. If you keep yourselves from these, you will do well. Farewell.”

Acts 21:25

>But as for the Gentiles who have believed, we have sent a letter with our judgment that they should abstain from what has been sacrificed to idols, and from blood, and from what has been strangled, and from sexual immorality.”