---
bibliography: references.bib
---

# Pergamum

\$ /pi /epsilon /rho /gamma /alpha /mu /omega /sigma \$ = Height / Elevation / Citadel

## Geography

Located on a mountain - easily defendable. No steep cliff like Sardis. Not a port city.

## History

Settlement 8th Century BC

Controlled by Alexander the Great.

After Alexander's death, empire split among Alexander's generals.

-   Lysimachus takes control of western Asia
-   Seleucus takes control of territories to the East
-   Seleucus attacks Lysimicus in order to expand his territody
-   Philestaerus - steward of the city of Pergamum for Lysimicus: Switches sides to Seleucus just prior to the battle for Pergamum.
-   Seleucus wins and rewards Philestaerus, who became wealthy, and first Attelid king.

212 BC: Alliance of Rome and Attelus I attacks Antiochus III the Great and wins. Rome allows Attelus to keep control of Pergamum (as they were skeptical that they could control a large modern city.)

190 BC Battle of Magnasia

189 BC Treaty of Apamea

133 BC Antiochus III wills his empire to ROme

129 BC Pergamum become capitol of province of Asia. 150 AD Ephesus is on the ascendency and overshadows Pergamum. Ephesus has a port, which Pergamum does not.

31 BC Octavian defeats Mark Anthony at Battle of \_\_\_.

29 BC Pergamum asks Octavian to allow it to be the first city to construct a temple for emperor worship. Octavian agrees, on the condition that temples are also constructed at Ephesus and Nicea to Roma and Julius Caesar.

### Ius Gladii

Only Roman governors and the emperor were given the right of the sword, meaning the power to execute capital punishment. Roman legionnaires carried a double-egded sword. Emporer carried a pear-shaped sword ( to emphasize their power of life and death). Usual mechanism of capital punishment was the gladiatorial ring.

## Throne of Satan

Sites of pagan worship in Pergamum which might be candidates for "Throne of Satan":

### Temple of Zeus

Locatedin Bergama museum in Berlin. Built aroung 170BC by Eumenes II

Rev 8:34 Incense smoke rising off the altar

Tabernacle - 12 loaves of show-bread, which are exchanged every Sabbath. Priests eat bread after Shabbat -\> "I provide for you"

### Temple of Athena

Second largest library in the ancient world

Julius Caesar invaded Alexandria and destroyed the libary. Mark Anthony plunders library in Pergamum in retaliation.

Built in 36BC as first temple.

Athena was goddess of wisdom (cf "I am the way, the truth, and the life")

### Trajan Temple

Built 98-117 AD for emperor worship.

Original temple built in 29 BC for emperor worship has not been found.

26 AD 2nd temple built for Smyrna - Neokorus for Tiberius. This means that for 50 years, Pergamum was leading site for emperor worship.

98 AD Trajan selects Pergamum as site for construction of temple for emperor worship. Platform for temple supported by Arches (similar to arches supporting Herod's Temple in Jerusalem)

### Letter to Ephesians

Ephesians 1-3: Christian identity. Chapters 4-6: Christian behavior. Fits pattern of identity -\> Calling -\> Conduct.

> Our fight is not against flesh and blood.

Armour of God is defensive

Roman soldiers forbidden to protect hamstrings (so that they would not be comofrtable running away from the enemy).

Need a community to stand firm similar to how Roman soldiers were able to create a strong defensive position by interlocking their shields ("tortus")

Right relationships \>\> Right behaviors

### Temple to Dionysus

Theater began in ancient Greece

Springtime festival: Dionysus was resurrected from the dead each spring. Dionysus was patron saint of theater and the arts.

Patron diety of arts and theater

Tragedy and Comedy

Pantomine - One actor plays all roles. Suggestive and sensual

Mime - Dialog without masks. Crude. Very popular. Could be performed in the agora

Eph 5

> Not even a hint of ... or coarse jesting

Symposia = "drinking together"

Convivium - less sexual and more intellectual

Roman relationships were all transactional

XXX Room - Stone couches with pillows. Women and boys available

Libation - drink offering to the Gods

Thomas Cahill - fragment of 4C BC comedy which comments on how a symposia typically progresses

Jesus - I am the resurrection and the life (reference ot Dionysus)

Jn 6

> I am the living bread which comes down from heaven. Unless you eat my flesh and drink my blood, you have no part of me. Your ancestors ate the manna in the desert and died.

"Room clearing speech"

John doesn't include Last Supper

Took \| Blessed \| Brokc \| Gave - these elements were in the feeding of the 5,000

Podium Hall - could accomodate 70 worshippers of Dionysus. Meat (sacrificed on altar) and wine - body and blood of Dionysus.

## Demeter = Ceres

Goddess of grain

Jn

> I am the bread of life.

Only way to get into sanctuary is to be sprinkled with the blood of piglets.

Included an altar to an unknown god.

## Aescylupian

Aescylapius - Father is Apollo. God of inspiration.

Epiparis

Most famous hospital in ancient world

Snakes - symbol of regeration (they shed their skin)

If healed -\> Can commission terra cotta body parts

Library

Stoa = Covered collonade

Sacred Spring

Galen - practiced at Pergamum

Pythea - Oracle to speak to people for treatment regimens from gods

Soter = savior
