---
bibliography: references.bib
---

#Ephesus

Ephesus a gateway city for Troas to the East, connecting the Aegean to Asia. Only more highly traveled area is Israel.

## Geography

Located at mouth of Cayster River as it flows to Aegean Sea. Silting of the Cayster River meant that the Aegean sea moved further and further away from Ephesus over the centuries. At the time of Paul, the river

Mount Coressus - Hiked

Mount Pion - across valley from Coressus with two humps

Mount Ayasoluk - Ottoman castle (after 1340 AD)

Locations of Ephesus

-   Ionian city at base of Moutn Pion
-   Lydian/Persian/Greek city near the Artemisian
-   Lysimicus moved to valley between Coressus and Pion (294BC - 650AD)
-   Byzantine city near Ayasoluk

Theater at base of mount Pion could hold 20,000 people

Road goes from amphitheater to harbor = "Harbor Street"

Theater to covered building - Marble Street

Building to smaller theater - Curetes Street.

Commercial Agora between theater and villas (inside large flat-roofed structue)

Civic agora - large square with theater ( by contrast, Perga had one agora)

Magnesin gate - near bend in road outside parking lot.

5 mile wall built by Lysimicus to protect city

Stadium on NorthEast

### History

Origin myth - Amazons, all-woman tribe of Hittites from the Black Sea region, founded Ephesus and cult of Artemis. Amazons were reputed to have cut off their breasts after child-rearing so as not to interfere with their skill as archers

Ephesus founded 1900BC

Local peoples 1100 to 1000 BC (during time of David - Uriah the Hittite is from Turkey)

Greek colonists -\> Greek influence. Settlement situated city off North side of Moutn Peon about 1000BC until 550BC (off North end of Mt Peon).

560BC - Lydian King Cresus takes control of city, then moves city further twoards Mount Ayosolyou.

546BC - Croesus is defeated by Cryrus I of Persia

334 BC Ephesus is conquered by Alexander the Great, who preserves the city.

301 BC Alexander the Great dies and his generals fight for control of the kingdom.

294 BC Lysimicus gains control of Ephesus, moves city to between Mount Coressus and Mount Pion, and builds a 5-mile wall to protect city.

282 BC Seleucus Nicator defeats Lysimicus. Philaterus was the city steward of Pergamum, who just before the battle sides with the Selucids, who subsequently defeat Lysimicus.

Battle of Magnasia

Seleucids lose to Romans and Attelids

133BC Attelid III dies and wills empire to Rome.

Added to Roman Provice of Asia 129 BC

First Century AD: Ephesus suppants Pergamum as foremost city in Asia. Fourth larges city in Roman empire behind rome, ayrian antioch, Alexandria. Ephesus and Syrian Antioch ar similar sin sizse Minimum 250,000 people in Ephesus in Paul's day.

#### Artemis Temple

Ephesus was temple keeper (neokoros) for Artemis. Temple was largest in the world, of which only a solitary column remains. Off North end of Mt Pion headed towards mount Ayasoluk. Temple located outside city gates because by legnd a meteor fell from the sky in a swampy area. Birthplace of Artemis was behind Mount Coressus in Mount Ortygia.

## Paul in Ephesus:

Acts 18:18-21

> Paul stayed many days, set sail (from Corinth) with Aquilla and Priscilla.

Paul was trying to come to Ephesus, but was prevented by the Holy Sprit. On Second missionary journey, drops off Aquilla and Priscilla.

Acts 14:24-28

> Jew named Apollo. Had been instructed in the way of the Lord. Knew only baptism of John...proving from the scriptures that Jesus was the Christ

Acts 19:1

> While Apollos was in Corinth. Paul took interior road (3rd Journey - has with him since Lystra = Timothy)

Acts 20:31

> Be on your guard. For 3 years I have never stopped warning you with tears.

Acts 19:22

> Timothy stayed in Asia and pastors the church

II tim 4:11-13

> Only Luke with mith me. Get Mark. I sent Tichicus to Ephesus.

Tichichus is pastoring in Ephesus. Timoty was buried at Ephesus. Luke is buried at Ephesus. After this. John comes to Ephesus and becomes pastor in Ephesus.

### Mary Mother of Jesus

On the cross, Jesus says" "John behold you mother, Mother, behold your son."

Two theories regarding later life of Mary mother of Jesus

-   Came with John to XXX
-   Jesus's brothers took care of her.

### Aphrodesian Theater

Aprodesian theater: Built in 2c AD and could hold 1750 people in Bouleterion. Constructed in Hellenistic period (Begins with Alexander the Great 334BC ff). Bouleterion used for meeting of boule = city council, during which time only council members could enter. Otherwise could be used as Odeon (lecture hall)

Acts 19:

Paul spends 18 Months in Corinth -\> Ephesius. Leaves Priscilla and Aquilla

Apollos - needs to hear about holy spirit -\> receives Holy Spirit -\> goes elsewhere

Acts 19:1

> Apollos at Corinth. Paul took road through interior to Ephesus. Have you heard of Holy Sprit\> -\> Jhn's Baptism. thhey were baptized in name of Jesus and holy spirit am on them and they spoke in tongues and prophesized

John (the Baptizer)'s mission was a baptism of repentence in order to prepare the way for the Messiah. Events of Acts 19 occur during Paul's third missionary journey (54-55AD), 25 yeaers after resurrection - people still are talking about John's baptism. *John's ministry must have had a profound impact*, as the gospel of Jesus had still not been procolaimed in Ephesus.

### Paul's Journeys

-   First journey 46-48

-   Acts 15 council 49-50

-   2nd Journey 50-53

-   Third journey 53-54-57 AD.

-   Arrested in Jerusalem

-   Cesearii Phillipi

-   Rome in 60AD - 61AD

-   Paul released 61AD

-   Rearrested 67AD

-   Martyred by Nero 68AD

## False teaching a major problem in Ephesus

## Sorcery

Seven sons of Sceva

> Jesus I know, and I know about Paul, but who are you?

Ephesus was the center of magic in the Roman empire. Curses, Voodoo, incantations. Paul has a power that is coming from a different source of power. Drachama = 1 days wage. When sorcers burn their scrolls, 50,000 drachamas went up in flames. What a way to start a church! The healing through handkerchiefs only happens in Ephesus - perhaps becase the citizens were open to supernatural powers. Sorcery is NOT cult worship (of emporers or GrecoRoman gods).

## Artemesian Temple

Four times size of Parthenon. 400+ feet long, 200+ feet wide, with forest of 127 columns. Temple had several functions:

-   Destination for pilgrims
-   Banking
-   Governmental inscriptions
-   Asylum
-   Debtors
-   Poor and Needy

Artemesian cult controlled 70,000 acres of agriculture. Alexander offered money to help rebuild. 1000s of pilgrims came for Spring festival of Artemis

At new testament time, temple was seventh one built on the site, having been rebuilt and removated multiple times.

Located at site of meteroite falling. Traditional birthplace behined moutn Paresis.

July 21, 356 BC Herostratus burned down temple with oil lamps and rags July 21, 356BC (Alexnder the Great's birthday). Rulers banned use of his name. "Herostatic fame" is now in common parlance. Dishonoring that goddess would let the temple burn. Date is birthdate of Alexander the Great. "Back Storu? goddess left her post to attend the birth of Alexander the Great

Richest sancuary apart for oracle at Delphi

Ortesia - sacred grove where Artemis was born, described as "paradise" = paradeisos

Acts 19:

> There arose a great disturbance about The Way. Demetrius a silversmith brought in no little business for the skilled wrokers "You know, that we received a good business, and how Paul has convinced... practically the whole province of Asia.

Acts 19

> They shouted for two hours: "Great is Artemis" in the theater

Preitanus (City Clerk) quieted the crowd. (It took him two hours to get there)

> People of Ephesus, doesn't all the world know that Ephesus is neocorus of the temple of Artemis and her image that fell from heaven. Since these facts are undeniable.

> Though they have neither robbed tamples or blasphemed...

> IF then, Demetrius and his associates have a grievance, they can bring it to the procounsel.

> As it is, we are in danger of being charged with rioting, since there is no reason for it. With that, he dismissed the assembly.

Paul was having a massive impact on the city, not by tearing down their gods, but by elevating the gospel.

### Theater

Renovations started 60AD

Ima Kevea + media kevea + summa kevea
