---
bibliography: references.bib
---

---
output:
  pdf_document: default
  html_document: default
---

# Thursday

## Angels of the Churches

7 starts and 7 lamp stands.

Who are angels? Ethos of the community

Roland Worth. John addresses angel and church simultaneously (interchangeable).

?Angel is bishop or pastor. (Jezebel reference). There isn't a single pastor or bishop. Paul is raising up a lead of pastors or leaders. John oversees leaders of each of the communities of house churches.

Angel is also messenger. Could this be a person identified in each church as a courier.

### Ears to hear

Is 6:8-10

> Whom shall I send? Send me. Be ever hearing, but never understanding... otherwise, they may hear and understand.

Jer 5:21

Written to Southern Kingdom after Babylonian exile of the Northern Church

> Hear

Ex 12:2

> You are living among a rebellous people, who have ear and do not hear

Ez 3:27

Ps 115:1-8

> Idols have eyes but do not see, and have ears but do not hear

Mark 8

After feeding of 4000

> Why are you taking about having no bread? Are your hearts hardened? Do you have eyes to see and not see and ears to hear and do not hear?

Later, Jesus goes to Bethsaida. Heals blind man. (partial healing is an illustration of disciples hearts)

> Do you see anything?

# Prene - Temple to Athena

11C BC city founded

350BC re-founded due to silting of Meander river. Pre-planned city. Hippodamian planning: all roads run at right angles. Prene is best type-site for Greek city design.

Population at zenith: 15,000

334 BC - Alexander the Great visits. City surrenders. Miletas chose to resist and was besieged by Alexander. During siege, Alexander visits and helps dedicate temple to Athena. Alexander the Great welcomed into Ephesus as well. (Provides funds for rebuilding temple to Artemis, which was declined as it was thought inappropriate for one god to contribute to another).

Attelids control Prene

Attelid III wills empire to Rome

### Temple

Inscription: "King Alexander dedicated this temple to Athena". Athena is the goddess of war (and wisdom). Alexander sought to change the world through Hellenism. Athena: I am the way, the truth, and the life

Designed by Pythius (also designed mausoleum at Honocarnasus, also a 7 wonder of the ancient world). At the time, wrote a treatise on how temple was constructed, which was used as a manual until 2C BC.

Emperor worship was major competitor to the gospel for the early church. Italians did not easily accept divinity of cesear, but Asia did accept divinity of the emperors.

### Alexandrian

### Synagogue

6C AD

Inscription of menorah

Torah closet

Early church met in homes in residential areas.

No church buildings until 4C AD (due to legalization of Christianity)

We needed to hear story anew.

Museum - If you show up in Asia Minor and want to preach the good news (divine man, believe on Jesus and be saved) - people would say "got that"

## Church's ministry to the Culture

How did church change Asia minor? Community. Christians acted (deeds) contrary to culture. Paul: We are God's workmanship (poema) to walk

Love others as yourself (contrary to transactional relationship in Roman society).

Caring for others (adoption of infants exposed and those abandoned in the market).

Sexual ethic of Christians was different from roman society

Treatment of women and children and slaves. Women were seen as more than object of male gratification.

No longer male/female, master/slave, Jew/Greek - both in justification and in dignity.

Genesis - God created us in his image: male and female.

Major beef with Christians:

1)  Destruction of social order. Roman economy was based upon slavery. Spartacus in 73BC broke out of gladiator in Capua near bay of Naples and led a slave revolt. Two motivations: median averages - Amassed 90,000 people who joined revolt, most slaves rescued from country villas. Fort was on Mount Vesuvius. He gave dignity to slaves. 71BC Crassus put down revolt -\> crucified 6000 rebels along Appian way. Communicated message about revolt and giving dignity to slaves.

2)  Redefined power. If you sacrifice to Cesar, you give to him. If you worship Jesus, he will sacrifice for you.

3)  As Roman society decayed, divinity of emporers started to make less sense. Tiberius - last 10 years he abrogates responsibility and leaves Sejanus in charge and Tiberius departs for a life of debauchery. Local governors (such as Pilate) needed to take more responsibility. Caligula. Problem with assassinating a diving ruler. Augustus was golden age of empire (44 years of peace, then dies a natural death).

4)  Tangible power of the Christian community, in contrast to distant deity of the emperor. House churches: unity and ?underground economy in Thyatira, to avoid participation in guilds. Broke bread together. Studying together. Mutual prayer. Evangelizing. Singing together.

Colossians

> As you teach and admonish one another, with worshiping and singing

House church - Lord's supper.

Example: Church at Corinth

I Cor

> I have no praise for you. Your meetings do more harm than good. Some of you go ahead with your own private suppers. As a result, some are hungry and others get drunk. Don't you have homes to eat or drink in? Or do you despise the church to humiliate those who are poor. For I received from the Lord what I have passed on to you. In the same way, after the supper he took the cup.

At the heart of Jesus' message is sacrifice for others.

> In this way you celebrate the Lord's death until he comes.

> Whoever eats or drinks in an unworthy manner, drinks judgement

whoever eats and drinks without discerning the body of Christ (ie knowing needs of the body).

Some sickness is the result of sin...

Sin is destructive in when it takes root.

> But if we were more discerning, ... but we are being disciplined

6)  Christians believed in the Holy Spirit, which was personally present in people's lives.

Julius Caesar ascended on a comet to the right hand of Saturn. He was present but distant.

Town Clerk: Paul has never maligned the gods.

Role of the leader is to close the gap.

Need the testing of God's work (rather than criticizing other church leaders from the stage).

### Message of Jesus

Barakh - Hebrew work can be translated - to bless or uplift or give praise to. Most usage is to bless God. "Blessed are you Lord our God"... Literal meaning is to bend a knee. We kneel to bring attention to God. When we bend a knee, we make someone else bigger. When we humble ourselves, we make someone else greater

Phil 2:5-8

> In your relationships with one another, have the same... as Jesus, who took on humanity. Did not consider his \_\_\_ came in human likelness, became obedient to the cross

Matt 20:25-30

> The rulers of the Gentiles lord it over the them, and their high officials exercise authority over them. Not so with you, Instead, whoever . Just as the Son of Man did not come to be served, but to serve, and give his life as a ransom for many.

Cross was the most humiliating instrument in the ancient world.

John 13: 1-5

> Jesus knew that it was time... He now showed them the full extent of his love. He knew that the father had put all things under his. He got up and began to wash the disciples feet.

Jesus bends a knee as he washes his feet. A rabbi would never wash the feet of his students. Jesus had put Peter in the servant's position. John is in seat of predominance. Peter should have washed everyone's feet, and Jesus's washing of feet is a sign Peter had missed his responsibility

John 13: -17

> when he had finished washing. Do you understand what I have done? You call me teacher and Lord, Now that I have washed your feet, you should wash one another's feet. No servant is greater than is master, nor a messanger than the one who sent. You will be blessed if you do this.

Who bends the knee to whom in your world? In your marriage?? Among friends? At work? At church? In family?

Proposal on bended knee -\> made a promise to bend a knee in the marriage.

=\> Jesus was at the core of our life, as he served and sacrificed for us.

John 17:20-23

> High priestly prayer. My prayer is not for them along, but also for , that all of them may be one, just as I am in you and you and me, that they may believe,.... that they may be brought to complete unity.

Heb 10:

> Since we have a great priest, let us draw near to God, having our hearts sprinkled. Let us hold unswervingly . Let us consider how we can spur one another on to good deeds. Let us not abadndone meeting together, as some are in the bhabit of doing, proclaiming the coming of Christ.

Agora manager

Priene Calendar Inscription 9BC of Caesar Augustus

> Since providence has orderd all things, whome she filled with all virtue, sending him as a savior for us, that he might end war, surpassing all previous benfactors... And since the birthday of Agusuts was the beginning of the evangelion of Caesar.

# Oracle

120 columns - each takes 20,000 hours of work

Built around sacred spring

Delphi - adyton built over a fissue in the rock, which released gas which put priests in a trance.

Adyton - Inside naiskos = inner temple. Adyton is inner chamber inside naiskos.

Pythea - sitting on top of tripod, inhaling vapors -\> trance. Priest would stay outside adyton and ask pythea. Oracle would speak back the answer is a different voice than her own. She was taken over by spirit of Apollo. Pythea = oracle. ONce named, couldn't leave. At times, she would become hysterical, and would be dead in a few days.

Minority report (Tom Hanks)

Similar to what was happening at aescalypeon in Ephesus. Was there a dark magic operating?

Oracles in ancient world: 3/6 are in Asia Minor.

Paul in Ephesus: Statements which could be understood by Ephesian audience.

Acts 20:20 I have taught you publicly from house to house.

Acts 20:27 I have not hesitated to proclaim to you the whole will of God

Acts 20:33 I have not coveted anyone silver, gold, or clothing.

Ephesians 1:7-9 In him we have redemption in his blood, in the riches of his grace, making known to us the mystery of his will, which he set forth in Christ.

Mystery =/= secret. Secret is intended to be kept hidden, but a mystery is intended to be revealed over time.

Oracle was a central fact of Roman culture known throughout Asia Minor. People travelled long distances in order to hear from the gods to ask important questions.

We have all the words of God in our bibles. Are we ignoring the wisdom of God's revealed word? THe word of God is what guides our path.

## Holiness

Paul's letter

Rom 1:7

> Grace to you and peace

I Cor 1:1

> 

Eph 1:1

> Paul and apostle

> Paul and Timothy

Col 1:1-2

> Paul and Timothy

Col 3:12

> As God's chosen People

Heb 3:1

> Fix your thoughts

Genesis 1: Human space and God's space overlap.

After fall, sin has brought separation between human space and God's space.

Tabernacle so that I can dwell among them. Needs to build a space where there can be overlap between human dnd God's space where he can overlap with

586 BC Babylonians burn temple.

537 BC Cyrus: Pleaple can go back

516BC temple re-dedicated -\> becomes massive structure on Temple Mount

John : HE tabernacled among us.

Jesus: Do not leave until you recive the spirit.

God changes his location from tabernacle to his spirit.. God's presence is no longer contained within a temple. Language going forward: You are a new temple.

Eph 2:19 Consequently, you are nolonger foreigners and strangers. With Christ Jesus him self ad the christ

.. in which God lives by his spirit.

You are God's temple. You are that temple.

Your body is the temple (singular)

Jesus came to heal saparation bewtwen hold God and unholy people.

Never been about the sapce, (eg the chuth building) but about the people

REve 21 - God's dwelling is now wiht his people. Complete reddec

God meets with Israel Ex 19 and 20 - time of Shavoat = {pentacost)}

Mt Saini occurs at Pentacost

Changein identity - Saint who sins (rather than sinner saved by grace)

Early church prior to 400Ad diddnt' have buildings

God changed his adress form the temple to the church (people)

Once Christianity became legal, built buildigs and decline followed.

I cor 3:16-17 If anyone destroys temple, God will destroy that person. Does this mean factionality in the Church? Disunitiy = destroying unity

Shaloam - Started in Shaloam - shattered -\> rebuilt -\> restored in final days of history.

# Miletas

Two harbors

-   

-   Lions harbor

Ciy abandoned by silting of Meander river and malaria from swamp formed by Meander river

6C BC most prosperous Greek city in country. 60,000 people. One of first cities to mint coins (along with Sardis).

494BC Persians faught against Miletas - Island of Laude -\> defeats Miletas' fleet, which made Miletas inferior to Ephesus.

Third imerial cult temple here (Pergamum, Smyrna). Caligula followed. Caligula wanted temple built while he was lliving. Neocorus for Caligula.

After 3D BC - Meander silting, city declined.

Largest agora ever built in Greek world. Heropolis had largest in Roman world

Miletas was neocorus for Apollo (Ephesus \~ Artemis).

Apollo Sanctuary in Miletas and temple in Didyma

II Tim 4:20

> Erastus stayed in Corinth. I left trophamis sick in Miletas

Greek inscription: "The place of the Jews who are god-fearers".

# Wrap up

How do you say goodbye to someone you believe you won't ever see again.

Acts 20

> (end of Paul's third missionary journey): Trying to get to Jerusalem in time for Pentacost.

> Arrived at Miletas. (Paul had decided to avoid Ephesus to arrive in Jerusalem by Pentacost.

Paul sent to Ephesus for the elders of the church. When they arrived, Paul said: You know howI lieved the whole time I ws with you,from the first itme I entered the provicne of Asia I served the lord with great humility despite the plots of the Jews, but taught you publically from house to house. I have proclaimed to Jews and Greeks that they need to place their faith in jesus. But the spirit warns me... But my only aim is to finish the race adn complete the task the Lord has given me, the task of testifying to the good news of God's grace. I know none of you will ever see me again.Therefore, I declare to you today that I am innocent of anyone' blood. I have given you the whole counsel of God. Be shepherds of the church of God. Even from youor own number, soe will arrive, so be on your guard. Remember that for three years I never stopped warning you night and day with tears. I have not coveted anyone's silver, or gold or clothes. In everything I did, I worked to help the weak... It is more blessed to give than to receive.

Departed from harbor at Miletas.

Started with Paul in a harbor.

I Cor 11:1

> Be imitators of me, as I am of Christ

Could we say: "Be imitators of me, as I follow Christ"?

Help the weak (those on the under-side of power)

Admonish with tears

Be shephers of the church - a group of peole leading another group of people

Every where I go, the spirit warns me that hardship is headed my way.

I held nothing back

No retirement from Kingdom work

John records:

John 17:3 Jesus's prayer for us:

> This is eternal life, that they know you I have brought you glory on earth by finishing the work you give me to do.

Artists - Last 10% makes or breaks the work...

(strengthen your hands to finish strong)
