project:
  type: book

book:
  title: "Discipleship"
  author: "JCS"
  date: "3/14/2026"

  chapters:
    - index.qmd
    - part: "Premarital Coaching"
      chapters:
      - CatchingFoxes.qmd
      - CatchingFoxes_questions.qmd
      - premarital_coaching.qmd
    - part: "BEMA"
      chapters:
      - concepts.qmd
      - tools.qmd
      - prophets.qmd
      - samuel_kings_chronicles.qmd
      - roman_history.qmd
      - matthew.qmd
      - revelation.qmd
    - part: "CMDA"
      chapters:
      - mentorship_academy.qmd
    - part: "Carl Truman"
      chapters:
      - desecration_of_man.qmd
      - strange_new_world.qmd
    - part: "Jon Tyson"
      chapters:
      - jon_tyson.qmd
      - man_year1.qmd
    - part: "NT Wright"
      chapters:
      - surprised_by_hope.qmd
    - part: "Turkey"
      chapters:
      - 10-turkey.qmd
      - 14-antalya.qmd
      - 14-colossae.qmd


bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual


### 3/20 add index