---
bibliography: references.bib
---

# Acts

Peter's Speech

3000 added that day - callback to Mount Zion - 3000 died after Golden calf

Jesus is raised on First Fruits. 50 days later is Shavuot

Between First Fruits and Savuot, no harvesting of the corners of the fields

## Ascension

Ananias and Sepharia

Problem wasn't holding back the money, but lying to the disciples.

At the beginning of a move of God, there are examples of judgement to communicate that it needs to be done right:

-   Aichan

-   Touching the ark of the covenant

-   Collecting wood on the Sabbath

## Acts 5 - Peter's healing powers

> 12 Now many signs and wonders were regularly done among the people by the hands of the apostles. And they were all together in Solomon's Portico. 13 None of the rest dared join them, but the people held them in high esteem. 14 And more than ever believers were added to the Lord, multitudes of both men and women, 15 so that they even carried out the sick into the streets and laid them on cots and mats, **that as Peter came by at least his shadow might fall on some of them**. 16 The people also gathered from the towns around Jerusalem, bringing the sick and those afflicted with unclean spirits, and they were all healed.

### Isaiah 32

> Behold, a king will reign in righteousness, and princes will rule in justice. ^**2**^ Each will be like a hiding place from the wind, a shelter from the storm, like streams of water in a dry place, **like the shade of a great rock in a weary land.** ^**3**^ Then the eyes of those who see will not be closed, and the ears of those who hear will give attention. ^**4**^ The heart of the hasty will understand and know, and the tongue of the stammerers will hasten to speak distinctly.\
> ^**5**^ The fool will no more be called noble, nor the scoundrel said to be honorable. ^**6**^ For the fool speaks folly, and his heart is busy with iniquity, to practice ungodliness, to utter error concerning the [Lord]{.smallcaps}, to leave the craving of the hungry unsatisfied, and to deprive the thirsty of drink. ^**7**^ As for the scoundrel—his devices are evil; he plans wicked schemes to ruin the poor with lying words, even when the plea of the needy is right. ^**8**^ But he who is noble plans noble things, and on noble things he stands.

Isaiah 32 speaks of the messiah. Perhaps the "great rock" is Peter (Petros).

Marty Solomon: Jews are looking for a messiah who ushers in the Kingdom.
