---
bibliography: references.bib
---

# Drew Tucker Key Questions:

### Chapter 1:

-   I start by having each person share their personal testimony.

-   How would you describe your present relationship with the Lord (spiritual disciplines, intimacy etc.)?

-   What would be one area of spiritual growth that you believe you need help in?

-   Tell me the story of you two meeting, courting, engagement.

-   What did you learn about marriage from your family of origin that you’d like to emulate?

-   What would you like to do differently?

-   Commitment to purity (victories, struggles)?

-   Have you talked about past sexual sin, abuse, involvement?

Answers given generally set the pace for where the conversation goes next.

### Chapter 2:

Page 47 - Question #4 “What do you think it means to seek Christ and his Kingdom in your marriage?

### Chapter 3:

What kind of rhythms do you have set in your lives for regular accountability - encouragement in a life of repentance and obedience?

Page 58 - Question #7 “What do you tend to run after for comfort, refuge, or deliverance? Do you run to sports, food, career, isolation, or something else?”

### Chapter 4:

Page 73 - Questions #1-2 Explain what “Let no man separate” means to you

What difficulties do you foresee in leaving your original family in order to be joined to your husband or wife? Share ways in which you could be too attached to or dependent upon your father, mother, or siblings - whether this involves their approval, respect, money, or advice

Page 77 - Questions #5-6 Share your desires for having children or not having children Share your fears about having children

### Chapter 5:

I usually start this meeting with a talk on the practice of identifying evidences of grace in one another. The practice of being on the lookout for places where you see the Spirit of God doing good work in one another and making that a regular practice/culture in marriage. I then ask them to practice - tell me one place you see in your fiancé that the Lord is clearly at work - actually - talk to each other. Then I ask them to identify one evidence of grace in their relationship.

How is a covenantal view of marriage different from a contractual view of marriage (or pg 84, Q1)?

Explain your perspective on divorce. Is it an option as you go into marriage? Usually looking for solid understanding of covenant and generally want to hear from a couple that divorce is a last resort.

### Chapter 6:

-   Pg 105 - Question #2 If there are things that he wants to talk about - I will engage. But for the most part I spend this time talking about what it means to be a biblical man / husband. God given responsibility to lead, serve, and protect. What is your view of biblical headship & submission?

### Chapter 7:

-   What is your view of biblical headship & submission?

-   Pg 130 - Q4

-   Pg 131 - Q5

-   Pg 137 - Q8

### Chapters 8-9:

I probably lean less heavily on book questions for these chapters. I’m generally after a cohesive understanding of how each saw conflict handled in their family of origin and how they’ve tended to handle conflict as a couple thus far. This almost always becomes a conversation about communication. When conflict enters - is your fiancé the one you are in conflict with or are you two united to deal with the conflict? What does it look like to be “on the same team” against a particular conflict? Put into the practice - regularly asking one another - “If you knew I wouldn’t get defensive or angry - what is one thing you think I could do to be a better husband / wife to you?"

### Chapter 10:

How did your conversation about this chapter prior to our meeting go? Are there specific ways I can serve you two as y’all prepare for sexual intimacy?

### Chapter 11:

Who is the spender? Who is the saver? What does it look like for you two to prioritize kingdom values in your financial stewardship as a married couple? What is your current work/life balance? Areas of struggle or opportunities for growth? Do you need help with budgeting or other financial preparations?

### Chapter 12:

No specific questions I lean on here. This usually winds up being more of a discussion of expectations based on the accumulated information I have from meeting with the couple over time.
