---
title: "6 Becoming a Wife"
output: pdf
---

| Husband | Wife |
|----|----|
| Joyful assumption of sacrifice | Joyful honoring of husband's will and position |
| for the eternal good of his spouse | for the eternal fruitfulness of her husband |
| for the glory of God | for the glory of God |
| =\> Submission to Christ | =\> Submission to Husband as unto the Lord |

## Genesis 2

> Then the LORD God said, “It is not good for the man to be alone; I will make him a helper suitable for him.” Out of the ground the LORD God formed every beast of the field and every bird of the sky, and brought them to the man to see what he would call them; and whatever the man called a living creature, that was its name. The man gave names to all the cattle, and to the birds of the sky, and to every beast of the field, but for Adam there was not found a helper suitable for him. So the LORD God caused a deep sleep to fall upon the man, and he slept; then He took one of his ribs and closed up the flesh at that place. The LORD God fashioned into a woman the rib which He had taken from the man, and brought her to the man. The man said,

> “This is now bone of my bones, and flesh of my flesh; She shall be called Woman, because she was taken out of Man.”

> For this reason a man shall leave his father and his mother, and be joined to his wife; and they shall become one flesh. And the man and his wife were both naked and were not ashamed. (vv. 18–25)

## Suitable helper

Helper: "A powerful ally who makes a willing choice to support or submit to someone's leadership"

Hebrew: Ezer עֵזֶר

> We wait in hope for the Lord; he is our help and our shield. Ps 33:20

Temporal, visible, living picture of the eternal, invisible, living reality of Christ and His church

Wife- display attitudes, affections, activities that Christ should have towards the church

## Wives need to be filled with the Spirit to fulfil their biblical roles:

Eph 5- Be filled with the Spirit

We work out our salvation

Phil 2:12-13

It is God who is at work in you

Power for obeying comes from God

John 15:5 I am the vine

Submission + Headship starts in the Godhed

> Wives, be subject to your own husbands, as to the LORD. For the husband is the head of the wife, as Christ also is the head of the church, He Himself being the Savior of the body. But as the church is subject to Christ, so also the wives ought to be to their husbands in everything. (Eph. 5:22–24)

God is the head of Christ I Cor 15:28

...As to the Lord

...In everything - except Sin- Christ would not lead the church into sin...

Submission to Christ overrules submission to husband

.. As is fitting in the Lord = fitting to a Christian Woman

> Wives, in the same way submit yourselves to your own husbands so that, if any of them do not believe the word, they may be won over without words by the behavior of their wives, when they see the purity and reverence of your lives. Your beauty should not come from outward adornment, such as elaborate hairstyles and the wearing of gold jewelry or fine clothes. Rather, it should be that of your inner self, the unfading beauty of a gentle and quiet spirit, which is of great worth in God's sight. For this is the way the holy women of the past who put their hope in God used to adorn themselves. They submitted themselves to their own husbands, like Sarah, who obeyed Abraham and called him her lord. You are her daughters if you do what is right and do not give way to fear. \[1Pe 3:1-6 NIV\]

Woman's source of hope and protection: her hope in God (I Peter 3:5)

```         
A wife who is learning to be subject to her husband “as to the LORD” is learning to speak to her husband in kind and respectful ways. She seeks to fulfill his desires for their household without begrudging them or resenting what they cost. She is learning to give herself more freely in sexual union. She appreciates the opportunity to serve him. She is praying to be “a suitable helper” (see Gen. 2:18), in every sense of the phrase. The wife who is learning to honor her husband “as to the LORD” longs to speak the truth in love to her husband. She refuses to nag and criticize him. She shares concerns with her husband but tries not to demand or threaten. When he sins against her, she gently confronts him for his own good and the pleasure of Christ. If he responds in pride and rejects all her petitions, then she carefully, courageously, and prayerfully seeks help from a trusted friend or from others in the body of Christ. She prays for reconciliation with her husband, not retribution. When she is afraid, she prays and runs to God for strength, faith, and wisdom. When life seems to be crumbling, she runs to Christ first, then to her husband. She trusts the Holy Spirit with the sanctification of her husband. The wife who loves her husband does not expect him to provide her sense of value and purpose in life. She looks to God to be her God and Savior. She believes herself to be “chosen of God, holy and beloved” (Col. 3:12), and longs to walk securely in the promises of God. She is learning to repent often and to seek God’s forgiveness. She even repents before her earthly husband and seeks his forgiveness. If she understands and walks in the Scripture with more maturity than her husband, then she also walks humbly before God and refuses to view her husband in a condescending way. She wants to help her husband love God according to God’s sense of time and perspective. Increasingly she views her place in marriage as a privilege and gift from God, not as a chore and certainly not as a punishment. She is learning to keep her home well—to be faithful in every duty that the LORD assigns. A wife who loves her husband is learning to view her every attitude, thought, and action toward her husband as an expression of her love for Jesus Christ. (pp129-130)
```

#### Leaving and Cleaving

Gen 2:24 Men are instructed to leave their parents, but not women: (culturally) assumed that a woman leaves her Family because and through marriage. Grooms need to leave and are not given away'

Is this man someone you can entrust yourself?

Questions:

- Family of origin- How did you see your parents interacting in leading/following?

- Expectations about teamwork

- How did your accepting Christ change your expectations?

- How has the chapter challenged or encouraged your expectations?

- What do you anticipate will be difficult?

------------------------------------------------------------------------
