---
title: "6 Becoming a Husband"
output: pdf
---

## Biblical Roles - Why?

> To the woman he said, "I will make your pains in childbearing very severe; with painful labor you will give birth to children. Your desire will be for your husband, and he will rule over you." To Adam he said, "Because you listened to your wife and ate fruit from the tree about which I commanded you, 'You must not eat from it,' "Cursed is the ground because of you; through painful toil you will eat food from it all the days of your life. It will produce thorns and thistles for you, and you will eat the plants of the field. By the sweat of your brow you will eat your food until you return to the ground, since from it you were taken; for dust you are and to dust you will return." Genesis 3

**Relationships between Men and Women**

|   | Created | Cursed | Redeemed |
|----|----|----|----|
| Woman | Helper Suitable | Desire husband's role | Submitted |
| Man | Exercise Dominion | Lord it over wife | Self-sacrifice |
| Marriage | Be Fruitful and Multiply |  | Demonstrate Christ+Church |

## Be filled with the Spirit

Fulfilling our biblical roles in marriage requires being filled with the Spirit

> Eph 5:18-21: And do not get drunk with wine, for that is dissipation, but be filled with the Spirit, speaking to one another in psalms and hymns and spiritual songs, singing and making melody with your heart to the LORD; always giving thanks for all things in the name of our LORD Jesus Christ to God, even the Father; and be subject to one another in the fear of Christ.

Filled with the Spirit

- New creation
- Trusting/Honoring Good
- Strengthened in his power
- Not ruled by worldly desire
- Ruled by the lordship of Jesus

Relational results of being filled with the Spirit

- Speaking in psalms
- Singing/making melody
- Giving thanks
- Being subject to one another in the fear of Christ

## Biblical relationship

> Eph 5:25-33 Husbands, love your wives, just as Christ also loved the church and gave himself up for her, so that He might sanctify her, having cleansed her by the washing of water with the word, that He might present to Himself the church in all her glory, having no spot or wrinkle or any such thing; but that she would be holy and blameless. So husbands ought also to love their own wives as their own bodies. He who loves his own wife loves himself; for no one ever hated his own flesh, but nourishes and cherishes it, just as Christ also does the church, because we are members of His body. For this reason a man shall leave his father and mother and shall be joined to his wife, and the two shall become one flesh. This mystery is great; but I am speaking with reference to Christ and the church. Nevertheless, each individual among you also is to love his own wife even as himself, and the wife must see to it that she respects her husband.

*Is there anything in this description of roles that sounds difficult? Anything you don't agree with?*

*What's your understanding of how God intends men and women to relate to one another in marriage?*

## Men are called to lead as Christ led the church (p107)

> John 10:11 I am the Good Shepherd (who lays down his life

> Heb 12:2 For the joy set before Him endured the cross, despising the shame

> Col 3:19 Husbands love your wives and do not be embittered against them

Responsibilities of the Husband:

- Joyful sacrifice
- Speaking truth in love
- Praying for his wife
- Confront wife's sinfulness in a gracious way
- Exercise spiritual leadership when there is conflict, *to avoid bitterness*

## Men are called to nourish and cherish their wives p111

“For no one ever hated his own flesh, but nourishes and cherishes it” (Eph. 5:29).

### Men are called to understanding and showing honor p112

> Husbands, in the same way be considerate as you live with your wives, and treat them with respect as the weaker partner and as heirs with you of the gracious gift of life, so that nothing will hinder your prayers. (1 Peter 3:7)

Husbands need to recognize and understand his wife's vulnerable position in submitting to his leadership

Women and Men are 'factor equipped' for different roles within the family.

Fellow heirs - men are called to recognize the ways in which God speaks to and through your spouse (spiritual antennae)

*To ponder: In your coming marriage, are you likely to rely upon the Spirit and his strength or on your own strength?*

Pro Tip: Living out biblical roles of husband and wife requires risk and vulnerability.

> ```         
> So when a husband is called to love his wife as Christ loved the church, he is called to joyfully sacrifice himself for the eternal welfare of his bride. This sacrifice is an attempt to lead his bride toward the Father for her good and the Father’s glory. This service leads him to pray for sanctification and growth in his bride. A husband who loves his bride this way seeks to help her glorify and enjoy her eternal husband, Jesus Christ. A husband who is learning to love his wife just as Christ also loved the church is also learning to speak the truth in love to his wife. He learns to pay careful attention to her words and to receive her thoughts with thanksgiving. He strives to be tender and compassionate. He learns to pray with his wife and for his wife. He reads the Scripture with her and listens to her views about the Word of God. He longs to give himself sexually and exercises patience when she declines to give her body in return. He prays to serve his bride without expecting service in return. He initiates conversation. He confesses sin genuinely. He forgives her and refuses to hold grudges. A husband who is learning to love his wife just as Christ also loved the church is also learning to confront his wife’s sinfulness in a gracious way. He is learning not to avoid painful interactions or to pretend things are okay in marriage when they are not. If his wife thinks they need help in their marriage, he humbles himself and seeks the aid of wise friends or pastors. He leads his marriage toward Christ and the body of Christ. He leads it into regular worship and service in the church. He is learning to lead it in wise and generous use of money. He works hard at his job without living for his career. He works faithfully at his job, whether it pays well or not, simply because he loves God and his wife. He is learning not to LORD authority over his wife but to serve and encourage her in Christ. pp108-109
> ```

## Leaving Parents p 118

> For this reason a man shall leave his father and mother and be joined to his wife, and the two shall become one flesh. . . . So they are no longer two, but one flesh. What therefore God has joined together, let no man separate. (Matt. 19:5–6)

```         
The instruction for a son to honor his father and mother also changes from a call to obey and follow his parents into a call to show them respect and gratitude but not obedience. A son may seek wisdom from his father or mother, but he is never again to place himself beneath their direction and control. He may continue to receive biblical counsel and encouragement from his parents, but only as he would from brothers or sisters in Christ. (p108)
```

## Questions

What is your view of biblical headship and submission?

How did you see headship and submission lived out in your home growing up?

Share about a few men who were key examples for you growing up—for better or for worse. How did they treat the women in their lives? What did you see in them and learn from them?

Are there ways in which you anticipate it will be difficult to leave your parents?

How do you anticipate your relationship with your parents will change after you get married?
