---
bibliography: references.bib
---

# RVL Israel

God's people are called to be city gates, standing stones, and at the crossroads

Mashal - Hebrew Parable (Strong 4911)

Jesus stops funeral procession.- cf Elisha "A prophet has awakened in Israel"

## Cities

-   Always found on untillable land
-   Req water source - Place king can store food
-   Defensive position
-   Place of safety
-   Rich lived in cities
-   Surrounded by daughter villages

Don't weep for me, weep for yourselves. The enemies will throw your babies against the wall

You are a city on a hill

4000 extant parables from biblical times, but only two involve cities:

-   Hillel
-   A certain man when down to Jericho

### Gezer

-   Located on Via Maris near coastal plain and Aijalon Valley
-   4000BC Glassade
-   2000BC Cannanite
-   1300 DC Joshja
-   City not taken by Joshua. Egyptian king gave Gezer as dowry 950BC
-   Destroyed
-   Destroyed again by Babylon
-   Conquered 15 times in 3500 years

### Hazor

-   City in Northern Israel along Via Maris - Fortified by Solomon

### Jaffa = Joppa

-   Chief seaport to float cedars of Lebanon to Jersualem for the temple

## Trade Routes

-   Via Maris along coast

-   Kings's Highway east of Jordan Valley - more difficult than Via Maris

## Gates

-   Defensive
-   Define relationship to the world
-   Unusual to breach the gates
-   Place of commerce
-   Place of justice (mishpat) Boaz went to city gates
-   Lot - an elder in Sodom and Gomorrah
-   Crucifixion just outside city gates
-   After Babylonian captivity, Jews separated from wider society
-   Nehemiah rebuilt the gates

## Cannanite cosmology

-   World is conflict between chaos and order (Ma'at)

-   Yamm is Canaanite God of primordial chaos

-   Genesis - in the beginning it was chaos, and the spirit of God hovered over the earth

-   Plagues: 10 gods addressed by 10 plagues

-   Fall: return to chaos

-   Jesus: I am the gate

-   Care for the poor in your gate [@BibleNIV, Deuteronomy 15:7]

## Levant Geography

Coastal - Philistines Foothills

-   Can't farm due to chalk in soil
-   Shephelah

Judean Mountains

-   Farmed in terraces

Back Slope

-   12 miles
-   Wilderness

Desert

-   Rift Valley

Valleys - Run East West

-   Aijalon - Joshua made sun stand still [@BibleNIV, Joshua 10:12-13]

    -   Pass of Beth Horon - Macabees victory
    -   Road to Emmaus [@BibleNIV, Luke 24:13-35]

-   Sorek

-   Elah - David and Goliath

-   Lachish

Adullum - Story of two caves

Lachish

## Religious Movements [RVL](https://www.thattheworldmayknow.com/the-four-views-of-judaism)

### Pharisees

-   From Hasmodian freedom fighters of Maccabee era
-   6000 middle-class merchants
-   Accepted oral interpretation of OT
-   Suported synagogue for Torah study and interpretation
-   Strict, detailed obedience to Torah and oral law

### Saducees

-   Descended from Zadok, Solomon's highest priest
-   Formed 200BC
-   Priests who were wealthy, aristocratic, and Hellenistic
-   Only Torah as God's law
-   Temple was the only path to God
-   No bodily resurrection
-   Dominated Sanhedrin

### Essenes

-   Resisted Maccabees claim to high priesthood in 170BC
-   Preferred isolation in wilderness
-   Ritual cleansing
-   Unclear if origin from Pharisees or Saducees

### Zealots

-   Formed in opposition to Roman census 6 AD lead by Judas the Galilean
-   Extreme Pharisees living in Galilee
-   Similar theology to Pharisees, but only God could rule
-   Slavery was worst evil
-   Taxes due only to God (refused to pay Roman tax)
-   Adhered to Torah interpretation

## Standing Stones [RVL](https://www.thattheworldmayknow.com/standing-stones)

-   Matzevah = Testament to what God has done

-   Both lawful practice and pagan

-   I Peter 2- You are living stones

-   Jacob - Beth El - God has been here. Sets up standing stone

-   Joshua sets up standing stones in Jordan river [@BibleNIV, Joshus 4:3-9]

-   Moses sets up 12 pillars in [@BibleNIC, Exodus 24:4]

# Chronology

## Babylon

-Captivity 586BC - Origin of Scribe, Torah Teacher, Hasidim, Synagogue

## Persia - Post Exilic 500BC

-   Return from captivity
-   Temple rebuilt
-   Ezra, Nehemiah, Zerubbabel
-   Saducees

## Greece - 333 BC

### Ptolemies 333-198BC

-Jews left Judiasm -\> Hasidim renewed Torah Study

### Selucids - 198BC

-   Hellenism by force
-   Resisted by Hasidim

### Maccabees 167- 37 BC

-   Hasmodian family led revolt in 167 BC
-   Supported by Saducces
-   Became Hellenistic

### Rome 63 BC - 325 AD

-   Pompey subdued area in 63BC. Made treaty wiht Antipater of Idumea -\> Herod becomes king

## Negev

### Jericho

-   City of palm trees [@BibleNIV, Deuteronomy 34:3]
-   Herod's palace

### Masada

-   Eliezer Ben Yair and 960 people fled here in 70AD
-   POssible place were David fled [@BibleNIV, I Samuel 23]
-   Stronghold referenced in I Chronicles 12:8

## En Gedi

-   "Fountain of the Goat"

## Avdat

## Arad
