---
bibliography: references.bib
---

# Premarital Coaching

### Questions July 2025

Resources: Catching Foxes

Scope: How many couples are married in the church each year? Salos can manage 3 couples/year

Training a team

-   Need 1 or 2 other couples to help with counseling as needs increase

-   Read the Catching Foxes book

-   Training sessions with Drew and Jessie (and Jonathan and Kelly)

“Red Flags” - Need a plan for these scenarios:

-   Chastity - Couple is living together/sleeping together

-   Pornography

-   History of sexual abuse

Which scenarios are ones in which a pastor would want to be notified/involved during the premarital counseling course (eg pornography addiction)

Pornography When/How do we inquire? How do we triage how serious a pornography problem is? Inadvertent exposure Occasional Use Intensive use Compulsive use (addiction) What resources do we have to help men (and women) find victory? Who needs professional counseling for pornography? Is there a role for providing help for the whole congregation in battling pornography? (eg bulk purchase of covenant eyes software

Finances/Budgeting

Communications

Conflict resolution

Family planning (in the broadest context)

Date Nights Newlywed counseling

-   What should we plan to offer for counseling after the wedding?

#### Meeting with Drew/Jonathan August 2025

Can complete in 4-6-8 sessions

1.  Chapter 1

2.  Chapter 2 and 3

3.  Chapter 4 and 5

4.  Chapter 6 and 7

5.  Chapter 8 and 9

6.  Chapter 10 (meet separately)

7.  Chapter 11 and 12 (optional - budgeting)
