---
bibliography: references.bib
---

# Pre-Assyrian Prophets

Prophetic Themes

-   Idolatry (Source A)
-   Injustice (Source B)
-   Hope in the midst of judgement

## Amos - Plumbline (and ripe fruit)

Prophet to Israel

## Hosea - Prostitute

Prophet to Israel

## Micah - Judge {BEMA50}

Prophet to Judah

God is looking for tzedekah, but instead finds Tze'ekah

Hope: Surely I will gather you, Jacob, I wil bring together the remnant of Israel. .I wil bring them together like sheep in a pen, like a flock in its pasture. The placd wil throng with oeople. The one who breaks open the way wil go up befoer then. They will break through the gate and go out. Their king will pass before then, the Lord at their head.

Hezekiah is a King of Judah who repents (and God spares Judah)

## 1 Isaiah - Vineyard {BEMA51}

## Jonah - Potential {BEMA52}

## Nahum - Diyn {BEMA53}

Diyn - retributive justice (against Ninevah)

vs mishpat = restorative justice

## Zephaniah - T'shuvah (return) {BEMA54}

Prophecizes against the priests who set up a Molech sacrificial center (in Valley of Hinon)

## 2 Isaiah - Woe {BEMA55}

Isaiah 13-39

### Taunt against the King of Babylon

>12 “How you are fallen from heaven, O Day Star, son of Dawn!
>How you are cut down to the ground, you who laid the nations low!
>13 You said in your heart,‘I will ascend to heaven; above the stars of God I will set my throne on high; I will sit on the mount of assembly in the far reaches of the north;[c]
>14 I will ascend above the heights of the clouds; I will make myself like the Most High.’
>15 But you are brought down to Sheol,to the far reaches of the pit.
>16 Those who see you will stare at you and ponder over you:
‘Is this the man who made the earth tremble,who shook kingdoms,
>17 who made the world like a desert and overthrew its cities, who did not let his prisoners go home?’
>18 All the kings of the nations lie in glory, each in his own tomb;[d]
>19 but you are cast out, away from your grave,like a loathed branch, clothed with the slain, those pierced by the sword, who go down to the stones of the pit, like a dead body trampled underfoot.
>20 You will not be joined with them in burial,because you have destroyed your land, you have slain your people.

This passage has been applied to Satan, but context (before and after) states it relates to the King of Babylon

cf Hezekiah 28

## Isaiah 36

Format changes from poetry back to prose (like Kings)

## Jeremiah - Weeping {BEMA56}

Babylonian prophet

### Valley of Slaughter 7:30

Gehenna used 12 times in NT, 11 by Jesus. Derived from Geehenom = Valley of Hinnom. Actual valley outside Jerusalem. Also known as Topheth

> **7**:30 “For the sons of Judah have done evil in my sight, declares the Lord. They have set their detestable things in the house that is called by my name, to defile it. 31 And they have built the high places of Topheth, which is in the Valley of the Son of Hinnom, to burn their sons and their daughters in the fire, which I did not command, nor did it come into my mind. 32 Therefore, behold, the days are coming, declares the Lord, when it will no more be called Topheth, or the Valley of the Son of Hinnom, but the Valley of Slaughter; for they will bury in Topheth, because there is no room elsewhere. 33 And the dead bodies of this people will be food for the birds of the air, and for the beasts of the earth, and none will frighten them away. 34 And I will silence in the cities of Judah and in the streets of Jerusalem the voice of mirth and the voice of gladness, the voice of the bridegroom and the voice of the bride, for the land shall become a waste.\
> **8** “At that time, declares the Lord, the bones of the kings of Judah, the bones of its officials, the bones of the priests, the bones of the prophets, and the bones of the inhabitants of Jerusalem shall be brought out of their tombs. ^2^ And they shall be spread before the sun and the moon and all the host of heaven, which they have loved and served, which they have gone after, and which they have sought and worshiped. And they shall not be gathered or buried. They shall be as dung on the surface of the ground. ^3^ Death shall be preferred to life by all the remnant that remains of this evil family in all the places where I have driven them, declares the Lord of hosts.\
> **19** Thus says the Lord, “Go, buy a potter's earthenware flask, and take some of the elders of the people and some of the elders of the priests, ^**2**^ and go out to the Valley of the Son of Hinnom at the entry of the Potsherd Gate, and proclaim there the words that I tell you. ^**3**^ You shall say, ‘Hear the word of the Lord, O kings of Judah and inhabitants of Jerusalem. Thus says the Lord of hosts, the God of Israel: Behold, I am bringing such disaster upon this place that the ears of everyone who hears of it will tingle. ^**4**^ Because the people have forsaken me and have profaned this place by making offerings in it to other gods whom neither they nor their fathers nor the kings of Judah have known; and because they have filled this place with the blood of innocents, ^**5**^ and have built the high places of Baal to burn their sons in the fire as burnt offerings to Baal, which I did not command or decree, nor did it come into my mind— ^**6**^ therefore, behold, days are coming, declares the Lord, when this place shall no more be called **Topheth**, or the Valley of the Son of Hinnom, but the Valley of Slaughter.^**7**^ And in this place I will make void the plans of Judah and Jerusalem, and will cause their people to fall by the sword before their enemies, and by the hand of those who seek their life. I will give their dead bodies for food to the birds of the air and to the beasts of the earth. ^**8**^ And I will make this city a horror, a thing to be hissed at. Everyone who passes by it will be horrified and will hiss because of all its wounds. ^**9**^ And I will make them eat the flesh of their sons and their daughters, and everyone shall eat the flesh of his neighbor in the siege and in the distress, with which their enemies and those who seek their life afflict them.’

### 70 Years of Babylonian Captivity

> **25** The word that came to Jeremiah concerning all the people of Judah, in the fourth year of Jehoiakim the son of Josiah, king of Judah (that was the first year of Nebuchadnezzar king of Babylon), 2 which Jeremiah the prophet spoke to all the people of Judah and all the inhabitants of Jerusalem: 3 “For twenty-three years, from the thirteenth year of Josiah the son of Amon, king of Judah, to this day, the word of the Lord has come to me, and I have spoken persistently to you, but you have not listened. 4 You have neither listened nor inclined your ears to hear, although the Lord persistently sent to you all his servants the prophets, 5 saying, ‘Turn now, every one of you, from his evil way and evil deeds, and dwell upon the land that the Lord has given to you and your fathers from of old and forever. 6 *Do not go after other gods to serve and worship them, or provoke me to anger with the work of your hands.* Then I will do you no harm.’ 7 Yet you have not listened to me, declares the Lord, that you might provoke me to anger with the work of your hands to your own harm.

> 8 “Therefore thus says the Lord of hosts: Because you have not obeyed my words, 9 behold, I will send for all the tribes of the north, declares the Lord, and for Nebuchadnezzar the king of Babylon, my servant, and I will bring them against this land and its inhabitants, and against all these surrounding nations. I will devote them to destruction, and make them a horror, a hissing, and an everlasting desolation. 10 Moreover, I will banish from them the voice of mirth and the voice of gladness, the voice of the bridegroom and the voice of the bride, the grinding of the millstones and the light of the lamp. 11 This whole land shall become a ruin and a waste, and these nations shall serve the king of Babylon seventy years. 12 Then after seventy years are completed, I will punish the king of Babylon and that nation, the land of the Chaldeans, for their iniquity, declares the Lord, making the land an everlasting waste. 13 I will bring upon that land all the words that I have uttered against it, everything written in this book, which Jeremiah prophesied against all the nations. ^14^ For many nations and great kings shall make slaves even of them, and I will recompense them according to their deeds and the work of their hands.”

Jeremiah predicts the 70 years of Babylonian captivity, and draws the connection that Judah persisted in idolatry

Chronicles 36:20 comments on that prophecy

> ^**20**^ He took into exile in Babylon those who had escaped from the sword, and they became servants to him and to his sons until the establishment of the kingdom of Persia, ^**21**^ to fulfill the word of the Lord by the mouth of Jeremiah, until the land had enjoyed its Sabbaths. *All the days that it lay desolate it kept Sabbath, to fulfill seventy years.*

Chronicles draws the connection that the Babylonian captivity was related to failure to keep the Sabbath (and the other OT economic policies, including Shemitah and Jubilee)
