
---
bibliography: references.bib
---

# Revelation

Apocalytic literature - use of pictures and images to convey a message of hope to the present day

Zechariah (BEMA 68) - source


7 Stars - Reference toGreco-Roman culture and pagan understanding of the zodiac:  Sun, Moon, Mercury, Venus, Mars, Jupiter, Saturn

Written ?during reign of Domitian

### Ephesus - BEMA158

Revelation is written after Ephesians.  In the interim, Mt Vesuvius erupted in AD 79.  Oracle at Dephi said it was due to destruction of the temple in Jerusalem. Domation responds by trying to kill the Jews and their Gode -> persecurtion.

First love of Ephesus - Was it Jesus?  Or the unity that we see in the letter to the Ephesians?

### Smyrna. {BEMA176}

Known for production of myrh. Obsessed with death

Port city (modern day Izmir) predates Rome.  Temple to Rome and Roma.

Jewish contingent did not accept the inclusion of the Gentiles and excluded the Gentiles from the Jewish exclusion with the Romans (allowed Jews to pay a tax and be exempt from the requirement to worship Caesar)


## Resources:

Christ and the Caesars https://archive.org/details/20191113christandthecaesars

Christians: The firsrt 200 years.
VOl 1: The Veil is Torn
Vol 2: A Pinch of Insence

7 cities of the apocalypse and Roman Culture by Roland H Worth Jr

Days of Vengeance




