---
title: "Samuel - Kings - Chronicles"
bibliography: references.bib
---

# Matthew

Matthew compares Jesus to Herod the Great. (Luke compares him to Caesar)

Matt 25 Ten Virgins

3/119: Gate of Hell - Matthew 16

3/123: Heat of the Day Matthew 20

## 3/125: Matthew 21

Two sons: Zadok and Abiathar

Parable of Vineyard:

Isaiah 5

Saducees when they heard the parable assumed that the tenants in the parable are Rome, but Jesus is calling them out as the wicked tenants

The "fruit" of the vineyard is the good works of Israel

Perspective of the Saducees is clear in their response: He will bring those wretches to a wretched end, and he will rent the vineyard to toerh tenants who will give him his share of the crop at harvest.

Isaiah 61:1

The Spirit of the Sovereign Lord is on me,\
    because the Lord has anointed me\
    to proclaim good news to the poor.\
He has sent me to bind up the brokenhearted,\
    to proclaim freedom for the captives\
    and release from darkness for the prisoners,^\[[a](https://www.biblegateway.com/passage/?search=Isaiah%2061&version=NIV#fen-NIV-18845a "See footnote a")\]^\
^**2**^ to proclaim the year of the Lord’s favor\
    and the day of vengeance of our God,\
to comfort all who mourn,\
^**3**^     and provide for those who grieve in Zion—\
to bestow on them a crown of beauty\
    instead of ashes,\
the oil of joy\
    instead of mourning,\
and a garment of praise\
    instead of a spirit of despair.\
They will be called oaks of righteousness,\
    a planting of the Lord\
    for the display of his splendor.

^**4**^ They will rebuild the ancient ruins\
    and restore the places long devastated;\
they will renew the ruined cities\
    that have been devastated for generations.\
^**5**^ Strangers will shepherd your flocks;\
    foreigners will work your fields and vineyards.\
^**6**^ And you will be called priests of the Lord,\
    you will be named ministers of our God.\
You will feed on the wealth of nations,\
    and in their riches you will boast.

### Parable of Wedding Banquet

God is throwing a party, but in His way and at His time.

Man without wedding clothes - someone who doesn't recognize God's design, desire, or authority

cf Zephaniah 1

\[Zep 1:4-12 ESV\] 4 "I will stretch out my hand against Judah and against all the inhabitants of Jerusalem; and I will cut off from this place the remnant of Baal and the name of the **idolatrous priests** along with the priests, 5 those who bow down on the roofs to the host of the heavens, those who bow down and swear to the LORD and yet swear by Milcom, 6 those who have turned back from following the LORD, who do not seek the LORD or inquire of him." 7 Be silent before the Lord GOD! For the day of the LORD is near; the LORD has prepared a sacrifice and consecrated his guests. 8 And on the day of the LORD's sacrifice-- "I will punish the officials and the king's sons and all who array themselves in **foreign attire**. 9 On that day I will punish everyone who leaps over the threshold, and those who fill their master's house with violence and fraud. 10 "On that day," declares the LORD, "a cry will be heard from the Fish Gate, a wail from the Second Quarter, a loud crash from the hills. 11 Wail, O inhabitants of the Mortar! For all the traders are no more; all who weigh out silver are cut off. 12 At that time I will search Jerusalem with lamps, and I will punish the men who are complacent, those who say in their hearts, 'The LORD will not do good, nor will he do ill.'

## 3/126: Trapped by a Question: Matthew

Good Samaratian

Hillel vs Shammai

Render unto Cesaer
