---
title: "Suprised by Hope"
author: "N T Wright"
bibliography: references.bib
---

# Surprised by Hope

## Session 2

## Salvation -

Being saved *for* something rather than just being saved *from* something

Rom 8: Whole creation awaiting salvation

> 19 For the anxious longing of the creation waits eagerly for the revealing of the sons of God. 20 For the creation was subjected to futility, not willingly, but because of Him who subjected it, \[i\]in hope 21 that the creation itself also will be set free from its slavery to corruption into the freedom of the glory of the children of God. 22 For we know that the whole creation groans and suffers the pains of childbirth together until now. 23 And not only this, but also we ourselves, having the first fruits of the Spirit, even we ourselves groan within ourselves, waiting eagerly for our adoption as sons, the redemption of our body. 24 For in hope we have been saved, but hope that is seen is not hope; for who hopes for what he already sees? 25 But if we hope for what we do not see, with perseverance we wait eagerly for it.

## Judgement: God putting everything right

Paul in Athens: Acts 17

>Being then God’s offspring, hwe ought not to think that the divine being is like gold or silver or stone, an image formed by the art and imagination of man. 30 iThe times of ignorance jGod overlooked, but know he lcommands all people everywhere to repent, 31 because he has fixed ma day on which nhe will judge the world oin righteousness by a man whom he has appointed; and pof this he has given assurance to all qby raising him from the dead.”

Messiah will put the world right as God's agent 

Psalm 2

>“I will announce the decree of the Lord:
He said to Me, ‘You are My Son,
Today I have fathered You.
8 Ask it of Me, and I will certainly give the nations as Your inheritance,
And the ends of the earth as Your possession.
9 You shall break them with a rod of iron,
You shall shatter them like earthenware.’”
10 Now then, you kings, use insight;
Let yourselves be instructed, you judges of the earth.
11 Serve the Lord with reverence
And rejoice with trembling.
12 Kiss the Son, that He not be angry and you perish on the way,
For His wrath may be kindled quickly.
How blessed are all who take refuge in Him!


Psalm 9

>But the Lord sits as King forever;
He has established His throne for judgment,
8 And He will judge the world in righteousness;
He will execute judgment for the peoples fairly.
9 The Lord will also be a stronghold for the oppressed,
A stronghold in times of trouble;
10 And those who know Your name will put their trust in You,
For You, Lord, have not abandoned those who seek You.

Psalm 98

>May the sea roar and all it contains,
The world and those who dwell in it.
8 May the rivers clap their hands,
May the mountains sing together for joy
9 Before the Lord, for He is coming to judge the earth;
He will judge the world with righteousness
And the peoples with fairness.

Genesis - Man designed to reflect God's goodness into the world = made in the image of God (and to reflect praises back to God)

After Fall, God brings a plan for restoration that involves a faithful human being.  Jesus is the truly human being.  

I Corinthians 15 - Resurrection 

>21 For since by a man death came, by a Man also came the resurrection of the dead. 22 For as in Adam all die, so also in Christ all will be made alive. 23 But each in his own order: Christ the first fruits, after that those who are Christ’s at His coming, 24 then comes the end, when He hands over the kingdom to our God and Father, when He has abolished all rule and all authority and power. 25 For He must reign until He has put all His enemies under His feet. 26 The last enemy that will be abolished is death. 27 For He has put all things in subjection under His feet. But when He says, “All things are put in subjection,” it is clear that this excludes the Father who put all things in subjection to Him. 28 When all things are subjected to Him, then the Son Himself will also be subjected to the One who subjected all things to Him, so that God may be all in all.

The last enemy is death itself.  Death is the enemy.  Death is not defeated if we simply die and go to heaven.

Eph 2:8-10

By grace you have been saved . We are God's workmanship (lit poema = poem)

We are the instruments for God's redeeming work

God's judgement - God sorting it all out => means of God's salvation

We are bearers of wise healing creative judgement 

## Session 3

(church architecture - Kingdom of God - happens on earth as in heaven)

Jesus began launching the work of God's will on earth as it is in heaven

Two views of Jesus's second coming:

- Coming to complete the work of the Kingdom of God advancing in the earth
- Coming to snatch us away with Him to another place (heaven)

